'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Disc3, Download, Guitar, Headphones, LoaderCircle, Music2, Sparkles } from 'lucide-react';
import { loadStoredUser, refreshUser, saveUser, type StoredUser } from '@/lib/auth';
import styles from '../audio-spaces.module.css';

const GENRES=['Electronic','Cinematic','Indie pop','Ambient','Hip-hop','Jazz','Rock','R&B','Folk','Classical','Experimental'];
const MOODS=['Bittersweet','Euphoric','Mysterious','Hopeful','Melancholic','Tense','Dreamy','Playful','Triumphant','Intimate'];
const ENERGY=['Low','Slow build','Medium','Driving','Explosive'];
const TEMPOS=['Very slow · 60 BPM','Slow · 78 BPM','Midtempo · 100 BPM','Upbeat · 124 BPM','Fast · 145 BPM'];
const BARS=[22,40,58,76,47,88,63,34,70,94,55,80,41,67,86,49,73,31,59,91,65,39,77,52,84,61,35,69,89,48,74,55];
type TrackMode='instrumental'|'vocal'|'lyrics'; type Model='lyria-3-pro-preview'|'lyria-3-clip-preview';
type APIResult={result?:{audio_base64?:string;format?:string;mime_type?:string;size?:number;model?:string};credits_used?:number;usd_equivalent?:number;error?:string};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}>{label}{children}</label>}
function Select({value,values,onChange}:{value:string;values:string[];onChange:(value:string)=>void}){return <select value={value} onChange={(event)=>onChange(event.target.value)}>{values.map((item)=><option key={item}>{item}</option>)}</select>}

export default function LyriaSpace(){
  const [user,setUser]=useState<StoredUser|null>(null); const [model,setModel]=useState<Model>('lyria-3-pro-preview'); const [mode,setMode]=useState<TrackMode>('instrumental');
  const [genre,setGenre]=useState('Electronic'); const [mood,setMood]=useState('Bittersweet'); const [energy,setEnergy]=useState('Driving'); const [tempo,setTempo]=useState('Upbeat · 124 BPM');
  const [brief,setBrief]=useState('A late-night synthwave drive through rain-lit streets, nostalgic but propulsive, with a huge final lift.');
  const [instruments,setInstruments]=useState('Pulsing analog bass, gated drums, shimmering Juno pads, glassy arpeggios, soaring lead synth');
  const [structure,setStructure]=useState('[0:00] Filtered pulse and distant pads\n[0:20] Beat and bass enter\n[0:50] Wide melodic hook\n[1:20] Half-time breakdown\n[1:40] Full final refrain and clean ending');
  const [vocal,setVocal]=useState('Intimate lead vocal in the verses, layered harmonies opening in the chorus, clear diction.');
  const [lyrics,setLyrics]=useState('[Verse]\nCity sleeping in the rear-view glow\nMorning breaking on an open road\n\n[Chorus]\nWe are heading where the skyline ends\nNothing certain, everything begins');
  const [duration,setDuration]=useState('120'); const [format,setFormat]=useState('opus'); const [avoid,setAvoid]=useState('No abrupt cutoff, no spoken intro, no overly bright mastering');
  const [audio,setAudio]=useState(''); const [actualFormat,setActualFormat]=useState('opus'); const [size,setSize]=useState(0); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{const cached=loadStoredUser();setUser(cached);if(cached?.api_key)void refreshUser(cached.api_key).then((fresh)=>{if(fresh){setUser(fresh);saveUser(fresh);}})},[]);
  const seconds=model==='lyria-3-clip-preview'?'30':duration;
  const prompt=useMemo(()=>{const vocals=mode==='instrumental'?'Instrumental only. No vocals, chanting, or spoken words.':mode==='vocal'?`Include original sung lyrics. Vocal direction: ${vocal}`:`Use these lyrics exactly where natural. Vocal direction: ${vocal}\n\n## Lyrics\n${lyrics}`;return `Create a ${seconds}-second ${genre.toLowerCase()} track.\n\n## Creative brief\n${brief}\n\n## Musical direction\nMood: ${mood}. Energy: ${energy}. Tempo: ${tempo}.\nInstrumentation: ${instruments}.\n${vocals}\n\n## Structure\n${structure}\n\n## Avoid\n${avoid}\n\nFinish with a deliberate musical ending; do not cut off mid-phrase.`},[avoid,brief,energy,genre,instruments,lyrics,mood,mode,seconds,structure,tempo,vocal]);
  async function generate(){if(!user?.api_key){setError('Sign in to generate music');return}if(brief.trim().length<12){setError('Describe the track in more detail');return}if(mode==='lyrics'&&!lyrics.trim()){setError('Add lyrics first');return}setBusy(true);setError('');setAudio('');setStatus('Composing and mastering…');try{const response=await fetch('/api/service',{method:'POST',headers:{Authorization:`Bearer ${user.api_key}`,'Content-Type':'application/json'},body:JSON.stringify({service:'lyria',model,prompt,output_format:format})});const payload=await response.json() as APIResult;if(!response.ok)throw new Error(payload.error||'Music generation failed');const result=payload.result||{};if(!result.audio_base64)throw new Error('No audio returned');const next=result.format||format;const mime=result.mime_type||(next==='opus'?'audio/ogg;codecs=opus':next==='mp3'?'audio/mpeg':'audio/wav');setActualFormat(next);setSize(result.size||Math.round(result.audio_base64.length*.75));setAudio(`data:${mime};base64,${result.audio_base64}`);setStatus('Track ready');void refreshUser(user.api_key).then((fresh)=>{if(fresh){setUser(fresh);saveUser(fresh);}})}catch(reason){setError(reason instanceof Error?reason.message:'Music generation failed');setStatus('')}finally{setBusy(false)}}
  const usd=user?.credits_usd??(user?(user.credits*(user.credit_price_usd||.01)):0);const price=model==='lyria-3-clip-preview'?.04:.08;
  return <main className={styles.page}><header className={styles.header}><Link href="/tools"><ArrowLeft size={15}/> Creative spaces</Link><Link href="/account" className={styles.balance}>{user?`$${usd.toFixed(2)} USD`:'Sign in'}</Link></header>
    <section className={styles.hero}><div className={styles.eyebrow}><Music2 size={13}/> GOOGLE LYRIA 3 · OPENPATHS</div><h1>From direction to record.</h1><p>Compose full songs, cinematic scores, vocal hooks, and tight loops with structural control and compact Opus delivery.</p></section>
    <section className={styles.workspace}>
      <div className={styles.panel}><div className={styles.panelHead}><div><span>01 / SOUND</span><h2>Musical direction</h2></div><Guitar size={17}/></div><div className={styles.modelChoice}><button data-testid="lyria-pro" className={model==='lyria-3-pro-preview'?styles.activeModel:''} onClick={()=>setModel('lyria-3-pro-preview')}><span><b>Lyria 3 Pro</b><small>Full songs · 1–3 minutes</small></span><em>$0.08</em></button><button data-testid="lyria-clip" className={model==='lyria-3-clip-preview'?styles.activeModel:''} onClick={()=>setModel('lyria-3-clip-preview')}><span><b>Lyria 3 Clip</b><small>Hooks and loops · 30 seconds</small></span><em>$0.04</em></button></div><div className={`${styles.segment} ${styles.three}`}>{([['instrumental','Instrumental'],['vocal','AI vocals'],['lyrics','My lyrics']] as const).map(([value,label])=><button key={value} className={mode===value?styles.active:''} onClick={()=>setMode(value)}>{label}</button>)}</div><div className={styles.row}><Field label="Genre"><Select value={genre} values={GENRES} onChange={setGenre}/></Field><Field label="Mood"><Select value={mood} values={MOODS} onChange={setMood}/></Field><Field label="Energy"><Select value={energy} values={ENERGY} onChange={setEnergy}/></Field><Field label="Tempo"><Select value={tempo} values={TEMPOS} onChange={setTempo}/></Field></div><Field label="Instrumentation"><textarea rows={4} value={instruments} onChange={(e)=>setInstruments(e.target.value)}/></Field>{mode!=='instrumental'&&<Field label="Vocal direction"><textarea rows={3} value={vocal} onChange={(e)=>setVocal(e.target.value)}/></Field>}{mode==='lyrics'&&<Field label="Lyrics · [Verse] / [Chorus] / [Bridge]"><textarea rows={8} value={lyrics} onChange={(e)=>setLyrics(e.target.value)}/></Field>}</div>
      <div className={styles.panel}><div className={styles.panelHead}><div><span>02 / COMPOSE</span><h2>Creative brief</h2></div><Disc3 size={17}/></div><Field label="What should this feel like?"><textarea className={styles.script} rows={6} data-testid="lyria-brief" value={brief} onChange={(e)=>setBrief(e.target.value)}/></Field><Field label="Arrangement and timeline"><textarea rows={8} value={structure} onChange={(e)=>setStructure(e.target.value)}/></Field><div className={styles.row}><Field label="Duration"><select disabled={model==='lyria-3-clip-preview'} value={seconds} onChange={(e)=>setDuration(e.target.value)}>{(model==='lyria-3-clip-preview'?['30']:['60','90','120','180']).map((item)=><option key={item} value={item}>{item} seconds</option>)}</select></Field><Field label="File format"><select value={format} onChange={(e)=>setFormat(e.target.value)}><option value="opus">Opus · recommended</option><option value="mp3">MP3 · source</option><option value="wav">WAV · lossless</option></select></Field></div><Field label="Avoid"><textarea rows={2} value={avoid} onChange={(e)=>setAvoid(e.target.value)}/></Field><pre className={styles.promptPreview}>{prompt}</pre></div>
      <div className={styles.panel}><div className={styles.panelHead}><div><span>03 / MASTER</span><h2>Render track</h2></div><Headphones size={17}/></div><button data-testid="lyria-run" className={styles.run} disabled={busy} onClick={()=>void generate()}>{busy?<LoaderCircle className={styles.spin} size={17}/>:<Sparkles size={16}/>} {busy?status:`Generate track · $${price.toFixed(2)}`}</button><div className={styles.price}><span>{model==='lyria-3-pro-preview'?'Lyria Pro':'Lyria Clip'}</span><span>{seconds}s · {format}</span></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.output}><div className={styles.outputHead}><span>MASTER OUTPUT</span><span className={audio?styles.ready:''}>{audio?'READY':busy?'GENERATING':'WAITING'}</span></div><div className={`${styles.wave} ${audio||busy?styles.live:''}`}>{BARS.map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div>{audio?<><audio data-testid="lyria-audio" controls src={audio}/><a className={styles.download} href={audio} download={`manifoldgen-lyria.${actualFormat}`}><Download size={14}/> Download .{actualFormat}</a></>:<p className={styles.empty}>{status||'Your track will appear here'}</p>}</div><div className={styles.facts}><div><b>44.1 kHz</b><span>STEREO</span></div><div><b>{actualFormat.toUpperCase()}</b><span>FORMAT</span></div><div><b>{size?`${(size/1048576).toFixed(1)} MB`:'—'}</b><span>SIZE</span></div></div></div>
    </section></main>;
}
