#!/usr/bin/env python3
"""Run the same prompt across ManifoldGen video models and record real outputs.

Results land in scripts/seo_bench_results.json and frontend/lib/seo/bench-results.ts
(the data module behind /leaderboard, /compare/*, /best/*). Idempotent: completed
entries are skipped, so re-running picks up new models or retries failures.

Usage:
  python3 scripts/seo_bench.py                 # full matrix
  python3 scripts/seo_bench.py --only wan      # one model key
  python3 scripts/seo_bench.py --status        # show progress
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API = "http://127.0.0.1:8116"
RESULTS = ROOT / "scripts" / "seo_bench_results.json"
FRONTEND_RESULTS = ROOT / "frontend" / "lib" / "seo" / "bench-results.ts"

PROMPTS = [
    {
        "key": "human-motion",
        "label": "Human Motion",
        "prompt": "A dancer in a flowing red dress performs contemporary dance on a rain-slicked city street at night, neon reflections on wet pavement, slow-motion fabric trails, cinematic tracking shot",
    },
    {
        "key": "vfx",
        "label": "VFX",
        "prompt": "A massive whale swims through clouds above a remote mountain village at sunset, volumetric god rays, glowing mist trailing behind it, epic fantasy VFX shot",
    },
    {
        "key": "cinematic",
        "label": "Cinematic Landscape",
        "prompt": "Drone shot flying low over an endless lavender field at golden hour, wind rippling through the flowers, distant storm clouds on the horizon, anamorphic lens flare",
    },
    {
        "key": "product",
        "label": "Product Shot",
        "prompt": "A sleek matte-black smartwatch rotates slowly on a reflective obsidian pedestal, dramatic studio rim lighting, macro detail on the textured crown, premium product commercial",
    },
    {
        "key": "stylized",
        "label": "Stylized World",
        "prompt": "A paper-craft origami fox trots through a miniature cardboard forest, tiny paper leaves drift through the air, tilt-shift macro lens, warm afternoon light",
    },
    {
        "key": "camera-motion",
        "label": "Camera Motion",
        "prompt": "One continuous dolly shot pushing through the open door of a cozy late-night ramen shop toward a steaming bowl, steam swirling, shallow depth of field, warm practical lights",
    },
]

MODELS = [
    {"key": "manifold-h3", "name": "Manifold H3", "service": "h3_video", "model": "", "duration": 5},
    {"key": "ltx-2", "name": "LTX 2", "service": "video_generate", "model": "ltx-2", "duration": 6},
    {"key": "seedance-fast", "name": "Seedance 2 Fast", "service": "video_generate", "model": "seedance-2.0-fast-text-to-video", "duration": 5},
    {"key": "seedance", "name": "Seedance 2", "service": "video_generate", "model": "seedance-2.0-text-to-video", "duration": 5},
    {"key": "wan", "name": "Wan", "service": "video_generate", "model": "wan", "duration": 5},
]


def api_key() -> str:
    url = None
    for line in (ROOT / ".env").read_text().splitlines():
        if line.startswith("DATABASE_URL="):
            url = line.split("=", 1)[1]
    row = subprocess.run(
        ["psql", url, "-tAc", "select api_key from users limit 1"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    if not row:
        sys.exit("no API key in local DB")
    return row


KEY = api_key()


def request(path: str, payload: dict | None = None, timeout: int = 300) -> dict:
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        f"{API}{path}", data=data, method="POST" if data else "GET",
        headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())


def save(results: dict) -> None:
    RESULTS.write_text(json.dumps(results, indent=1, sort_keys=True))
    FRONTEND_RESULTS.parent.mkdir(parents=True, exist_ok=True)
    rows = ",\n".join(
        f'  "{k}": {json.dumps(v, sort_keys=True)}' for k, v in sorted(results.items())
    )
    FRONTEND_RESULTS.write_text(
        "// Generated by scripts/seo_bench.py — do not edit by hand.\n"
        "export type BenchResult = { status: string; video_url?: string; wall_seconds?: number; credits_used?: number; error?: string };\n"
        f"export const BENCH_RESULTS: Record<string, BenchResult> = {{\n{rows},\n}};\n"
    )


def find_url(obj) -> str | None:
    if isinstance(obj, str):
        return obj if obj.startswith(("http://", "https://")) and any(
            obj.endswith(e) or f"{e}?" in obj for e in (".webm", ".mp4")
        ) else None
    if isinstance(obj, dict):
        for k in ("video_url", "output_url", "url", "saved_image_url"):
            v = obj.get(k)
            found = find_url(v) if isinstance(v, (dict, list)) else (v if isinstance(v, str) else None)
            if found:
                return found
        for v in obj.values():
            found = find_url(v)
            if found:
                return found
    if isinstance(obj, list):
        for v in obj:
            found = find_url(v)
            if found:
                return found
    return None


def load() -> dict:
    return json.loads(RESULTS.read_text()) if RESULTS.exists() else {}


def run_cell(prompt: dict, model: dict, results: dict) -> bool:
    cell_key = f"{prompt['key']}:{model['key']}"
    if cell_key in results and results[cell_key].get("status") == "completed":
        return False
    print(f"[bench] {cell_key}: submitting", flush=True)
    t0 = time.time()
    try:
        payload = (
            {"service": "h3_video", "prompt": prompt["prompt"], "duration": model["duration"]}
            if model["service"] == "h3_video"
            else {
                "service": "video_generate", "model": model["model"],
                "prompt": prompt["prompt"], "duration": model["duration"],
                "aspect_ratio": "16:9",
            }
        )
        resp = request("/api/service", payload)
        result = resp.get("result", {})
        job_id = result.get("job_id") if isinstance(result, dict) else None
        url = find_url(result)
        while job_id and not url:
            time.sleep(15)
            status = request(f"/api/video-jobs/{job_id}")
            job = status.get("job") or {}
            job_status = status.get("status") or job.get("status")
            url = find_url(job.get("result") or status.get("result") or job)
            print(f"[bench] {cell_key}: {job_status} ({time.time()-t0:.0f}s)", flush=True)
            if job_status in ("failed", "cancelled"):
                raise RuntimeError(f"job {job_status}")
            if time.time() - t0 > 2400:
                raise RuntimeError("timeout")
        if not url:
            raise RuntimeError(f"no video url in response: {str(resp)[:200]}")
        results[cell_key] = {
            "status": "completed", "video_url": url,
            "wall_seconds": round(time.time() - t0), "credits_used": resp.get("credits_used"),
        }
        print(f"[bench] {cell_key}: DONE {url}", flush=True)
        return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:200]
        print(f"[bench] {cell_key}: HTTP {e.code} {body}", flush=True)
        results[cell_key] = {"status": "failed", "error": f"{e.code} {body}"}
        return True
    except Exception as e:  # noqa: BLE001
        print(f"[bench] {cell_key}: ERROR {e}", flush=True)
        results[cell_key] = {"status": "failed", "error": str(e)[:200]}
        return True
    finally:
        save(results)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="restrict to one model key")
    ap.add_argument("--status", action="store_true")
    args = ap.parse_args()
    results = load()
    if args.status:
        done = sum(1 for v in results.values() if v.get("status") == "completed")
        print(f"{done}/{len(PROMPTS)*len(MODELS)} completed; failed={len(results)-done}")
        for k, v in sorted(results.items()):
            print(k, v.get("status"), v.get("video_url") or v.get("error"))
        return
    for model in MODELS:
        if args.only and model["key"] != args.only:
            continue
        for prompt in PROMPTS:
            run_cell(prompt, model, results)


if __name__ == "__main__":
    main()
