import type { Faq } from '@/lib/seo/types';

export type PromptTool = {
  slug: string;
  name: string;
  h1: string;
  title: string;
  metaDescription: string;
  eyebrow: string;
  intro: string;
  audience: string;
  image: string;
  imageAlt: string;
  recommendedModel: string;
  modelHref: string;
  defaults: {
    subject: string;
    action: string;
    setting: string;
    camera: string;
    lighting: string;
    style: string;
    platform: string;
  };
  suffix: string;
  examples: string[];
  tips: string[];
  faqs: Faq[];
  relatedUseCases: string[];
};

const sharedFaq = (label: string): Faq[] => [
  {
    q: `Is the ${label} free?`,
    a: 'Yes. Building, copying, and remixing prompts is free and does not require an account. You only need an account when you choose to render the prompt.',
  },
  {
    q: 'Can I use the generated prompt in other AI video tools?',
    a: 'Yes. The output is plain text and works as a strong starting point in any text-to-video or image-to-video model. The one-click render button opens it in ManifoldGen.',
  },
  {
    q: 'What makes a good AI video prompt?',
    a: 'Name one clear subject action, one camera move, the environment, lighting, and intended visual style. A precise shot usually performs better than a long scene containing several competing actions.',
  },
];

export const PROMPT_TOOLS: PromptTool[] = [
  {
    slug: 'cinematic-ai-video-prompts',
    name: 'Cinematic AI Video Prompt Generator',
    h1: 'Cinematic AI Video Prompts',
    title: 'Cinematic AI Video Prompt Generator — Free Prompt Builder',
    metaDescription: 'Build cinematic AI video prompts with camera, lens, lighting, motion, and style controls. Free, no login, then render in ManifoldGen.',
    eyebrow: 'CINEMATIC PROMPT BUILDER',
    intro: 'Turn a loose shot idea into model-ready direction with a single action, deliberate camera language, lighting, texture, and pacing.',
    audience: 'Filmmakers, directors, previsualization artists, and creators who want shots that feel composed rather than randomly animated.',
    image: '/pseo/prompts/cinematic-director.webp',
    imageAlt: 'Cinematic director watching a surreal night scene through a production monitor',
    recommendedModel: 'Seedance 2',
    modelHref: '/tools/seedance-2',
    defaults: {
      subject: 'A lone astronaut crossing a flooded brutalist atrium',
      action: 'walks slowly as ripples spread around each step',
      setting: 'an abandoned lunar embassy at blue hour',
      camera: 'slow low-angle dolly-in on a 35mm anamorphic lens',
      lighting: 'cold skylight with a thin amber rim and volumetric haze',
      style: 'photoreal cinematic science fiction, restrained film grain',
      platform: '16:9 cinematic frame',
    },
    suffix: 'One continuous shot, natural temporal motion, coherent geometry, motivated camera movement, no captions, no watermark.',
    examples: [
      'A weathered lighthouse keeper climbs a spiral iron staircase during a storm, handheld camera following one level below, 28mm lens, lightning briefly reveals salt texture and wet stone, tense photoreal maritime drama, one continuous shot, no text.',
      'A dancer moves through a deserted marble museum after closing, slow lateral tracking shot, pools of moonlight and soft practical lamps, elegant fabric motion, quiet contemporary art-film grade, coherent body movement, no text.',
      'An old tram crosses a neon-soaked intersection in heavy rain, camera cranes from street-level reflections to the overhead wires, 40mm anamorphic lens, magenta and sodium-vapor contrast, grounded cyberpunk realism, no text.',
    ],
    tips: ['Write one shot, not a whole screenplay.', 'Use one primary camera move and one subject action.', 'Describe why the light exists: window, practical, moon, fire, or signage.'],
    faqs: sharedFaq('cinematic AI video prompt generator'),
    relatedUseCases: ['short-films', 'storyboard-previs', 'vfx'],
  },
  {
    slug: 'ai-product-video-prompts',
    name: 'AI Product Video Prompt Generator',
    h1: 'AI Product Video Prompts',
    title: 'AI Product Video Prompt Generator — Free Ad Shot Builder',
    metaDescription: 'Create polished AI product video prompts for reveals, macro shots, orbits, ecommerce ads, and paid social. Free and no login.',
    eyebrow: 'PRODUCT SHOT BUILDER',
    intro: 'Build clean product-film direction with controlled surfaces, camera choreography, commercial lighting, and platform-ready framing.',
    audience: 'Ecommerce teams, founders, performance marketers, and agencies producing product creative without a physical studio.',
    image: '/pseo/prompts/product-orbit.webp',
    imageAlt: 'Premium matte black perfume bottle in a cinematic studio product setup',
    recommendedModel: 'LTX 2.3',
    modelHref: '/tools/ltx-2-3',
    defaults: {
      subject: 'A matte black perfume bottle on a slab of wet obsidian',
      action: 'condensation beads gather while a soft mist passes behind it',
      setting: 'a minimal dark studio with a seamless charcoal backdrop',
      camera: 'slow 30-degree macro orbit with a gentle rack focus to the label',
      lighting: 'large soft key, narrow silver rim, controlled specular highlights',
      style: 'premium luxury product commercial, crisp material detail',
      platform: '9:16 paid social ad',
    },
    suffix: 'Keep the product silhouette, proportions, packaging, and label stable. Smooth commercial pacing, clean background, no invented text or logos.',
    examples: [
      'A white running shoe suspended above black water, slow push-in as a precise splash crown rises beneath the sole, hard side key and cool rim light, high-speed athletic commercial, sharp textile and rubber detail, 9:16, no text.',
      'A ceramic coffee cup rotates slowly on pale travertine while steam catches morning window light, 50mm macro lens, warm neutral palette, calm artisan commercial pacing, stable cup geometry, no text.',
      'A silver smartwatch emerges from folded charcoal fabric, camera arcs from the crown to the screen as a light sweep reveals brushed metal, premium tech launch film, controlled reflections, no extra objects or text.',
    ],
    tips: ['Describe materials and reflections precisely.', 'Ask for label and package stability explicitly.', 'Use macro, orbit, push-in, or rack focus—not all four at once.'],
    faqs: sharedFaq('AI product video prompt generator'),
    relatedUseCases: ['product-ads', 'ecommerce-videos', 'ugc-ads'],
  },
  {
    slug: 'anime-video-prompts',
    name: 'AI Anime Video Prompt Generator',
    h1: 'Anime Video Prompts',
    title: 'Anime Video Prompt Generator — Free AI Anime Prompt Builder',
    metaDescription: 'Generate anime video prompts with character action, shot type, lighting, atmosphere, and animation constraints. Free, no login.',
    eyebrow: 'ANIME SHOT BUILDER',
    intro: 'Direct readable anime shots with a locked character silhouette, purposeful pose, atmospheric depth, and animation-friendly action.',
    audience: 'Anime creators, music-video directors, fan animators, and visual storytellers creating stylized character shots.',
    image: '/pseo/prompts/anime-rain.webp',
    imageAlt: 'Original anime heroine beneath glowing lanterns in the rain',
    recommendedModel: 'Wan',
    modelHref: '/tools/wan',
    defaults: {
      subject: 'An original silver-haired courier in a red rain cape',
      action: 'looks over her shoulder as paper charms lift into the wind',
      setting: 'a lantern-lit mountain station during a summer storm',
      camera: 'medium profile shot with a slow parallax push-in',
      lighting: 'warm lantern glow against cool rain and distant lightning',
      style: 'hand-drawn cinematic anime, clean linework, painted backgrounds',
      platform: '16:9 anime sequence',
    },
    suffix: 'Original character design, consistent face and costume, clean anatomy, readable silhouette, restrained secondary motion, no subtitles, no watermark.',
    examples: [
      'An original shrine mechanic tightens a brass wing on a tiny clockwork bird, close insert shot, sunrise shafts through workshop dust, hand-drawn anime with detailed painted background, subtle hair and sleeve motion, consistent hands, no text.',
      'A young swordswoman waits alone on a commuter platform as snow begins to fall, slow dolly past foreground columns, pale blue dusk and warm carriage windows, cinematic anime realism, restrained breathing and fabric motion, no subtitles.',
      'Two original sky pirates sprint across the deck of an airship as clouds roll beneath them, energetic tracking shot, wind-driven coats and rigging, bold cel shading, coherent running cycle and ship geometry, no logos or text.',
    ],
    tips: ['Say “original character” to avoid accidental franchise imitation.', 'Lock hair, costume, and silhouette when identity matters.', 'Use secondary motion—rain, fabric, smoke—without overpowering the main action.'],
    faqs: sharedFaq('anime video prompt generator'),
    relatedUseCases: ['anime', 'music-videos', 'short-films'],
  },
  {
    slug: 'image-to-video-prompt-generator',
    name: 'Image to Video Prompt Generator',
    h1: 'Image to Video Prompts',
    title: 'Image to Video Prompt Generator — Animate a Still Cleanly',
    metaDescription: 'Write image-to-video prompts that preserve your source image while adding subject, camera, and environmental motion. Free, no login.',
    eyebrow: 'IMAGE MOTION BUILDER',
    intro: 'Describe only the motion your still needs. The builder separates subject movement, camera movement, and environmental movement so the source composition stays intact.',
    audience: 'Photographers, image artists, ecommerce teams, and creators animating an existing frame.',
    image: '/pseo/prompts/cinematic-director.webp',
    imageAlt: 'Production monitor showing a cinematic frame ready to animate',
    recommendedModel: 'Veo 3.1 Fast',
    modelHref: '/tools/veo-3-1-fast',
    defaults: {
      subject: 'The person in the source portrait',
      action: 'breathes naturally, blinks once, then turns slightly toward camera',
      setting: 'preserve the source background and composition exactly',
      camera: 'very slow 5% push-in with no reframing',
      lighting: 'hold the source lighting and exposure constant',
      style: 'preserve the source image style, texture, and identity',
      platform: 'source aspect ratio',
    },
    suffix: 'Treat the uploaded image as the exact first frame. Preserve identity, wardrobe, geometry, color, and background. No morphing, cuts, new objects, or camera shake.',
    examples: [
      'Treat the source product photo as the exact first frame. The bottle remains locked while tiny condensation droplets slide naturally; add a slow 20-degree orbit and a soft highlight sweep. Preserve label, shape, color, and backdrop. No morphing or new text.',
      'Animate the landscape photo with slow cloud drift, one breeze passing through the foreground grass, and a subtle parallax push-in. Hold the mountain silhouette, color grade, exposure, and horizon exactly. No new structures or cuts.',
      'The illustrated character blinks, smiles slightly, and raises one hand in a small wave. Add gentle hair and jacket secondary motion. Keep face, costume, linework, palette, and background unchanged. Static camera, no morphing.',
    ],
    tips: ['State what must remain unchanged.', 'Use small motion first; increase only after a stable result.', 'A camera move plus one subject action is usually enough.'],
    faqs: sharedFaq('image to video prompt generator'),
    relatedUseCases: ['image-to-video', 'product-ads', 'anime'],
  },
  {
    slug: 'seedance-prompt-generator',
    name: 'Seedance Prompt Generator',
    h1: 'Seedance Prompt Generator',
    title: 'Seedance Prompt Generator — Free Cinematic Prompt Builder',
    metaDescription: 'Create structured Seedance prompts for cinematic text-to-video, image-to-video, camera motion, and native audio. Free, no login.',
    eyebrow: 'SEEDANCE PROMPT BUILDER',
    intro: 'Build a shot around Seedance’s strengths: strong prompt adherence, cinematic motion, and synchronized scene audio.',
    audience: 'Creators using Seedance for cinematic final shots, dialogue-free scenes, ads, and social video.',
    image: '/pseo/prompts/cinematic-director.webp',
    imageAlt: 'Cinematic production scene illustrating a Seedance-ready prompt',
    recommendedModel: 'Seedance 2',
    modelHref: '/tools/seedance-2',
    defaults: {
      subject: 'A glassblower shaping a glowing vessel',
      action: 'turns the pipe steadily as sparks lift toward the rafters',
      setting: 'a dark brick workshop just before dawn',
      camera: 'slow shoulder-height arc from profile to three-quarter view',
      lighting: 'orange furnace light on the face with cool window fill',
      style: 'photoreal cinematic documentary, tactile skin and fabric texture',
      platform: '16:9 cinematic frame',
    },
    suffix: 'Synchronized audio: low furnace roar, soft glass hiss, distant workshop ambience. One continuous shot, coherent hands and tools, no narration or text.',
    examples: [
      'A cyclist enters a foggy suspension bridge at sunrise, camera follows low beside the rear wheel before rising to reveal the span, wet tire sound and light chain rhythm synchronized, cinematic realism, one continuous shot, no text.',
      'A chef plates a final dessert in a quiet open kitchen, 50mm close tracking shot, warm practicals and cool city bokeh, synchronized ceramic taps and soft room tone, exact hand-object contact, premium documentary style, no captions.',
      'A child launches a handmade paper rocket from a windy hill, camera cranes with it into the clouds, cloth and grass moving naturally, synchronized wind and laughter in the distance, warm 35mm family-film look, no text.',
    ],
    tips: ['Include the soundscape when using an audio-capable lane.', 'Give the camera a physical path.', 'Place important motion early in the prompt.'],
    faqs: sharedFaq('Seedance prompt generator'),
    relatedUseCases: ['text-to-video', 'short-films', 'product-ads'],
  },
  {
    slug: 'kling-prompt-generator',
    name: 'Kling Prompt Generator',
    h1: 'Kling Prompt Generator',
    title: 'Kling Prompt Generator — Free AI Video Prompt Builder',
    metaDescription: 'Build Kling video prompts with subject motion, cinematic camera direction, synchronized audio, and clean shot constraints. Free, no login.',
    eyebrow: 'KLING PROMPT BUILDER',
    intro: 'Create compact, filmable Kling directions for fluid physical motion, image animation, camera work, and native scene sound.',
    audience: 'Creators running Kling for cinematic scenes, energetic movement, image animation, and social video.',
    image: '/pseo/prompts/product-orbit.webp',
    imageAlt: 'Cinematic studio subject with strong rim lighting and camera movement',
    recommendedModel: 'Kling 3.0',
    modelHref: '/tools/kling-3',
    defaults: {
      subject: 'A street photographer beneath a transparent umbrella',
      action: 'steps into a puddle and raises the camera for one photograph',
      setting: 'a narrow Seoul alley after midnight rain',
      camera: 'smooth backward tracking shot at waist height, 40mm lens',
      lighting: 'soft shop-window light, red tail lights, wet street reflections',
      style: 'filmic urban realism with natural human motion',
      platform: '9:16 social film',
    },
    suffix: 'Synchronized rain, footsteps, and one camera-shutter click. Accurate limb motion, stable face and wardrobe, continuous shot, no captions.',
    examples: [
      'A rescue dog runs through shallow snow toward its handler, low tracking camera matching speed, powder kicks naturally from each stride, cold overcast daylight, synchronized breath and paw impacts, grounded cinematic realism, no text.',
      'A baker pulls a tray of croissants from an oven, gentle handheld push-in, warm tungsten practicals, visible steam and crisp pastry texture, synchronized tray slide and room ambience, coherent hands and oven geometry, no text.',
      'A vintage coupe rounds a coastal bend at golden hour, stabilized chase camera sweeps from rear three-quarter to side profile, suspension and reflections behave physically, engine and tire sound synchronized, premium automotive film, no logos.',
    ],
    tips: ['Keep human motion physically specific.', 'Name the exact sounds that should line up.', 'Use a stable source frame for identity-sensitive image-to-video.'],
    faqs: sharedFaq('Kling prompt generator'),
    relatedUseCases: ['tiktok', 'product-ads', 'short-films'],
  },
  {
    slug: 'veo-prompt-generator',
    name: 'Veo Prompt Generator',
    h1: 'Veo Prompt Generator',
    title: 'Veo Prompt Generator — Free Photoreal Video Prompt Builder',
    metaDescription: 'Generate Veo prompts for photoreal video, believable physics, camera direction, dialogue-free audio, and image animation. Free.',
    eyebrow: 'VEO PROMPT BUILDER',
    intro: 'Structure realistic Veo shots around physical cause and effect, observable texture, deliberate cinematography, and a restrained soundscape.',
    audience: 'Filmmakers, advertisers, and creators using Veo for photoreal scenes and physically believable image-to-video.',
    image: '/pseo/prompts/product-orbit.webp',
    imageAlt: 'Photoreal premium product scene with physically believable light',
    recommendedModel: 'Veo 3.1',
    modelHref: '/tools/veo-3-1',
    defaults: {
      subject: 'A marine biologist in a small research boat',
      action: 'leans over the rail as a whale surfaces alongside',
      setting: 'calm grey water off a rocky northern coast',
      camera: 'natural handheld medium shot, then a measured pan to the whale',
      lighting: 'soft overcast daylight with realistic water reflections',
      style: 'photoreal observational documentary, natural skin and fabric texture',
      platform: '16:9 documentary frame',
    },
    suffix: 'Believable water displacement, boat response, scale, and reflections. Synchronized ocean wash, hull creak, and breath. No narration, cuts, subtitles, or watermark.',
    examples: [
      'A ceramic artist opens a kiln and warm air rolls into a cool studio, locked medium-wide shot with a slight push-in, realistic heat shimmer and clay texture, synchronized latch and room tone, observational documentary realism, no text.',
      'A red fox crosses a quiet suburban garden at first light, long-lens camera pans gently from behind foliage, dew bends under its paws, distant birds and leaves synchronized, natural wildlife documentary, no cuts or text.',
      'A linen curtain lifts as a thunderstorm reaches an open apartment window, slow interior dolly toward the glass, changing daylight and physically accurate rain, synchronized room ambience and distant thunder, photoreal, no people or text.',
    ],
    tips: ['Describe physical interactions, not just appearance.', 'Use documentary language for natural results.', 'Keep generated speech out unless dialogue is essential.'],
    faqs: sharedFaq('Veo prompt generator'),
    relatedUseCases: ['text-to-video', 'documentary', 'product-ads'],
  },
  {
    slug: 'ai-camera-movement-generator',
    name: 'AI Camera Movement Generator',
    h1: 'AI Camera Movement Generator',
    title: 'AI Camera Movement Generator — Free Shot Direction Tool',
    metaDescription: 'Choose a subject and mood, then generate filmable dolly, crane, orbit, tracking, macro, handheld, and reveal directions for AI video.',
    eyebrow: 'CAMERA DIRECTION TOOL',
    intro: 'Replace vague “cinematic camera” language with a physical camera path, lens character, speed, subject relationship, and motivated reveal.',
    audience: 'Anyone who knows the scene they want but needs a clearer, more filmable camera instruction.',
    image: '/pseo/prompts/cinematic-director.webp',
    imageAlt: 'Director and cinema camera framing a dramatic night shot',
    recommendedModel: 'Manifold Video',
    modelHref: '/tools/manifold',
    defaults: {
      subject: 'A solitary figure at the end of a vast greenhouse aisle',
      action: 'stands still while leaves move in the ventilation draft',
      setting: 'a fogged glass greenhouse before sunrise',
      camera: 'start behind wet foreground leaves, slow dolly forward and rise into a clean eye-level reveal, 32mm lens',
      lighting: 'dim cyan dawn with isolated warm grow lights',
      style: 'atmospheric cinematic realism',
      platform: '2.39:1 widescreen shot',
    },
    suffix: 'The camera move must be smooth, physically achievable, and motivated by the reveal. Maintain stable subject scale and environment geometry, no cuts or text.',
    examples: [
      'Start inches above a rain puddle reflecting a theatre marquee; crane smoothly upward as a woman steps beneath the canopy, finishing in a medium profile at eye level, 28mm lens, continuous achievable move, stable architecture, no cuts.',
      'Track parallel with a runner through tall grass at knee height, 50mm lens and shallow depth of field, gradually fall one pace behind as the trail opens to a valley, smooth gimbal motion, coherent stride, no speed ramp.',
      'Begin on a macro detail of a watch crown, rack focus to the brushed case, then perform a restrained 25-degree orbit while pulling back to the full product, 85mm macro look, clean studio geometry, no text.',
    ],
    tips: ['State the start frame and end frame.', 'Tie the move to a reveal or emotion.', 'Lens, height, speed, and subject distance matter more than “cinematic.”'],
    faqs: sharedFaq('AI camera movement generator'),
    relatedUseCases: ['storyboard-previs', 'vfx', 'short-films'],
  },
  {
    slug: 'tiktok-ai-ad-prompt-generator',
    name: 'TikTok AI Ad Prompt Generator',
    h1: 'TikTok AI Ad Prompt Generator',
    title: 'TikTok AI Ad Prompt Generator — Free Vertical Video Builder',
    metaDescription: 'Build fast-hook TikTok AI ad prompts for UGC, product demos, problem-solution spots, and vertical paid social. Free, no login.',
    eyebrow: 'VERTICAL AD BUILDER',
    intro: 'Create a thumb-stopping opening shot with a single visual claim, readable product action, vertical composition, and space for native captions.',
    audience: 'DTC brands, paid-social teams, creators, and agencies producing vertical ad variants.',
    image: '/pseo/prompts/vertical-creator.webp',
    imageAlt: 'Creator filming a vertical product demonstration in a bright studio',
    recommendedModel: 'Kling 3.0',
    modelHref: '/tools/kling-3',
    defaults: {
      subject: 'A creator holding a compact travel espresso maker',
      action: 'shows the empty cup, presses once, then reacts as fresh espresso pours',
      setting: 'a bright, real apartment kitchen with a packed carry-on nearby',
      camera: 'close vertical handheld framing with a quick push toward the pour',
      lighting: 'soft window daylight, honest phone-camera exposure',
      style: 'authentic high-quality UGC, energetic but not overproduced',
      platform: '9:16 TikTok safe-area composition',
    },
    suffix: 'Show the result in the first two seconds. Keep hands and product stable. Leave clean upper and lower safe areas for captions; do not render text, logos, or watermarks.',
    examples: [
      '9:16 UGC ad: creator opens a messy desk drawer, holds up one compact cable organizer, then reveals the same drawer neatly arranged. Fast handheld match move, honest apartment daylight, clear before-and-after in two seconds, stable product and hands, no rendered text.',
      '9:16 product demo: close-up of a white sneaker entering muddy water, then a single wipe reveals the coating kept the fabric clean. Phone-camera realism, quick push-in on the result, natural outdoor light, one visual claim, no captions rendered.',
      '9:16 hook: exhausted traveler tries to sleep under bright hotel curtains, clips on a portable blackout panel, and the room immediately darkens. Authentic UGC framing, readable cause and effect, leave caption safe areas, no logos or text.',
    ],
    tips: ['Show the payoff before explaining it.', 'Make the product interaction readable without sound.', 'Leave safe areas for captions added in editing.'],
    faqs: sharedFaq('TikTok AI ad prompt generator'),
    relatedUseCases: ['tiktok', 'ugc-ads', 'product-ads'],
  },
  {
    slug: 'ai-real-estate-video-prompts',
    name: 'AI Real Estate Video Prompt Generator',
    h1: 'AI Real Estate Video Prompts',
    title: 'AI Real Estate Video Prompt Generator — Free Listing Shot Builder',
    metaDescription: 'Generate AI real estate video prompts for listing tours, exterior reveals, virtual staging, and property social clips. Free.',
    eyebrow: 'PROPERTY SHOT BUILDER',
    intro: 'Plan smooth, architecturally stable property shots that preserve room geometry, keep vertical lines straight, and make the light feel plausible.',
    audience: 'Agents, property marketers, architects, interior designers, and listing-media teams.',
    image: '/pseo/prompts/product-orbit.webp',
    imageAlt: 'Architectural interior lit for a polished commercial video',
    recommendedModel: 'LTX 2.3',
    modelHref: '/tools/ltx-2-3',
    defaults: {
      subject: 'A double-height living room with limewashed walls and oak joinery',
      action: 'linen curtains move lightly as morning sun reaches the floor',
      setting: 'a quiet coastal home overlooking native dunes',
      camera: 'slow stabilized walk-through from the entry to the window, 20mm rectilinear lens',
      lighting: 'natural morning light with warm practical lamps held subtle',
      style: 'premium architectural film, realistic materials and exposure',
      platform: '16:9 property listing video',
    },
    suffix: 'Preserve floor plan, walls, windows, furniture, and straight vertical lines. Smooth achievable camera path, no geometry warping, people, signs, captions, or watermark.',
    examples: [
      'Slow stabilized approach up a stone path toward a modern timber house at dusk, 24mm rectilinear lens, warm interior practicals against a blue-hour sky, native grass moving lightly, preserve building geometry and vertical lines, no people or text.',
      'Begin in the kitchen doorway and glide toward the island before a gentle pan reveals the garden, 20mm lens, soft overcast window light, premium architectural realism, exact cabinetry and room proportions, no warping or added furniture.',
      'Vertical 9:16 listing clip of a compact rooftop terrace, slow corner-to-corner orbit around the seating area, sunset city light, realistic plants and reflections, maintain railings and skyline geometry, clean caption safe area, no rendered text.',
    ],
    tips: ['Ask for rectilinear lenses and straight verticals.', 'Preserve the source floor plan explicitly.', 'Use slow paths; fast turns reveal geometry errors.'],
    faqs: sharedFaq('AI real estate video prompt generator'),
    relatedUseCases: ['ecommerce-videos', 'storyboard-previs', 'tiktok'],
  },
  {
    slug: 'ai-music-video-prompts',
    name: 'AI Music Video Prompt Generator',
    h1: 'AI Music Video Prompts',
    title: 'AI Music Video Prompt Generator — Free Visual Shot Builder',
    metaDescription: 'Build AI music video prompts with performance, rhythm, visual motif, camera movement, and edit-friendly framing. Free, no login.',
    eyebrow: 'MUSIC VIDEO SHOT BUILDER',
    intro: 'Translate mood and rhythm into one strong visual motif, a repeatable performance action, and camera movement that cuts cleanly on the beat.',
    audience: 'Musicians, labels, visual artists, directors, and creators producing performance or narrative music videos.',
    image: '/pseo/prompts/anime-rain.webp',
    imageAlt: 'Stylized performer under colored rain and glowing practical lights',
    recommendedModel: 'Manifold Video',
    modelHref: '/tools/manifold',
    defaults: {
      subject: 'A masked vocalist in a mirrored red rehearsal room',
      action: 'performs one restrained verse as reflections move out of sync',
      setting: 'an endless rehearsal space with a shallow layer of water',
      camera: 'slow circular Steadicam move that completes on the downbeat',
      lighting: 'deep red practicals, white strobe accents used sparingly',
      style: 'surreal high-fashion music video, tactile and cinematic',
      platform: '16:9 master with center-safe vertical crop',
    },
    suffix: 'One visual motif, edit-friendly action, stable performer identity, camera move timed to an eight-count. No lyrics, titles, logos, or watermark.',
    examples: [
      'A singer performs inside a transparent elevator moving through clouds, camera floats outside the glass and reaches profile on the eighth beat, soft silver sunrise, surreal dream-pop music-video realism, stable face and costume, no text.',
      'Three dancers repeat a sharp eight-count inside an empty supermarket at night, symmetrical wide lens, fluorescent aisles pulse subtly on downbeats, precise full-body choreography and reflections, bold contemporary music-video grade, no logos.',
      'An original anime drummer performs on a rooftop during warm summer rain, low circular camera move, city signs become soft abstract bokeh, clean hand-drawn linework and coherent drum contact, loop-friendly eight-count, no subtitles.',
    ],
    tips: ['Time movement to four or eight counts.', 'Repeat one motif across shots for cohesion.', 'Frame a center-safe master if you also need vertical crops.'],
    faqs: sharedFaq('AI music video prompt generator'),
    relatedUseCases: ['music-videos', 'anime', 'short-films'],
  },
  {
    slug: 'ai-storyboard-prompt-generator',
    name: 'AI Storyboard Prompt Generator',
    h1: 'AI Storyboard Prompt Generator',
    title: 'AI Storyboard Prompt Generator — Free Shot Planning Tool',
    metaDescription: 'Turn a scene beat into a clear AI storyboard frame prompt with subject blocking, lens, composition, lighting, and continuity notes.',
    eyebrow: 'STORYBOARD FRAME BUILDER',
    intro: 'Convert a story beat into a drawable frame: who is where, what the audience learns, how the lens shapes the moment, and what continuity must carry forward.',
    audience: 'Directors, agencies, animators, writers, and previsualization teams planning a sequence before generating video.',
    image: '/pseo/prompts/cinematic-director.webp',
    imageAlt: 'Director reviewing storyboard-like frames on a cinematic monitor',
    recommendedModel: 'GPT Image 2',
    modelHref: '/tools/gpt-image',
    defaults: {
      subject: 'A courier realizes the package has begun to glow',
      action: 'freezes with one hand still on the apartment door handle',
      setting: 'a narrow sixth-floor hallway during a power outage',
      camera: 'medium-wide over-the-shoulder frame, 35mm lens, package in the lower foreground',
      lighting: 'the package is the cool key light; distant emergency light adds a red edge',
      style: 'cinematic storyboard frame, clear value grouping, production-ready detail',
      platform: '2.39:1 storyboard panel',
    },
    suffix: 'Communicate one story beat in a single frame. Clear staging, readable eyeline, realistic screen direction, no panel borders, captions, arrows, labels, or watermark.',
    examples: [
      'Storyboard frame: an exhausted detective sees muddy footprints continue up a perfectly clean wall. Low medium-wide angle, detective foreground left, impossible trail leading to a dark ceiling hatch, 32mm lens, flashlight as motivated key, noir value study, one readable reveal, no text.',
      'Storyboard frame: a child hides beneath a banquet table while unfamiliar boots stop beside the cloth. Floor-level close wide shot, child in sharp foreground, boots soft beyond the tablecloth gap, warm party light above and cool hiding space below, clear suspense beat, no captions.',
      'Storyboard frame: two astronauts disagree silently while Earth rises behind them. Balanced two-shot through the station window, opposing eyelines, 50mm lens, pale monitor fill and blue Earth rim, restrained cinematic concept art, continuity-ready suits, no labels.',
    ],
    tips: ['Each frame should communicate one new fact.', 'Place foreground, subject, and reveal deliberately.', 'Track screen direction, wardrobe, and time of day between frames.'],
    faqs: sharedFaq('AI storyboard prompt generator'),
    relatedUseCases: ['storyboard-previs', 'short-films', 'vfx'],
  },
];

export function promptTool(slug: string): PromptTool | undefined {
  return PROMPT_TOOLS.find((tool) => tool.slug === slug);
}
