export interface CuratedSearchPage {
  slug: string;
  query: string;
  title: string;
  blurb: string;
}

const QUERIES: readonly string[] = [
  'cinematic portrait dramatic lighting',
  'rembrandt lighting portrait',
  'rain-soaked neon portrait',
  'film grain close-up portrait',
  'freckles natural window light portrait',
  'black and white studio portrait',
  'moody window light portrait',
  'golden hour side profile portrait',
  'teal and orange cinematic portrait',
  'shallow depth of field portrait bokeh',
  'vintage hollywood glamour portrait',
  'chiaroscuro dramatic portrait',
  'editorial beauty portrait dewy skin',
  'anamorphic lens flare portrait',
  'candid laughter portrait warm tones',
  'film noir detective office',
  'film noir femme fatale silhouette',
  'rainy street film noir',
  'venetian blind shadow noir',
  'film noir cityscape night',
  'smoky jazz club noir',
  'trench coat alleyway noir',
  'high contrast monochrome noir street',
  'film noir interrogation room',
  'noir lighthouse storm',
  'golden hour field portrait',
  'golden hour city skyline',
  'golden hour beach waves',
  'golden hour mountain ridge',
  'golden hour wheat field',
  'golden hour desert dunes',
  'golden hour rooftop silhouette',
  'golden hour forest sun rays',
  'golden hour lakeside reflection',
  'golden hour hot air balloon',
  'cyberpunk street market rain',
  'cyberpunk megacity skyline',
  'cyberpunk samurai neon',
  'cyberpunk hacker den monitors',
  'cyberpunk android portrait',
  'neon-soaked alley cyberpunk',
  'cyberpunk flying taxi traffic',
  'cyberpunk noodle bar steam',
  'cyberpunk graffiti wall night',
  'cyberpunk courier bike chase',
  'cyberpunk underground club lights',
  'cyberpunk rooftop rain skyline',
  'elven archer misty forest',
  'fantasy knight armor battlefield',
  'sorceress casting glowing spell',
  'dwarven blacksmith forge sparks',
  'orc warband marching',
  'fantasy castle siege dawn',
  'dragon rider above clouds',
  'ranger with longbow pine woods',
  'battle mage lightning storm',
  'elf queen throne room',
  'paladin radiant sword',
  'necromancer tower moonlit',
  'barbarian warrior snowy peak',
  'fairy glade moonlight',
  'griffin rider sea cliffs',
  'wizard study ancient tomes',
  'enchanted forest path lanterns',
  'bustling fantasy tavern market',
  'space station orbiting ringed planet',
  'alien jungle explorer expedition',
  'mars colony dome habitat',
  'starship bridge viewport stars',
  'derelict spaceship corridor',
  'mecha hangar maintenance crew',
  'terraformed moon base panorama',
  'wormhole jump starfield stretch',
  'alien bazaar crowded stalls',
  'cryosleep pod bay glow',
  'orbital elevator rising storm',
  'exoplanet twin sunrise landscape',
  'robot gardener greenhouse rows',
  'deep space nebula vista',
  'editorial fashion studio shoot',
  'evening gown red carpet moment',
  'haute couture runway walk',
  'avant-garde fashion sculpture silhouette',
  'fashion editorial desert dunes',
  'street style fashion week crowd',
  'monochrome fashion editorial wind machine',
  'silk dress flowing studio motion',
  'fashion editorial rooftop dusk',
  'bold color blocking fashion editorial',
  'vintage 1950s fashion editorial',
  'leather jacket urban editorial night',
  'tulle dress mid-motion editorial',
  'minimalist fashion white backdrop',
  'tokyo crossing at night crowd',
  'new york rainy umbrellas crosswalk',
  'market vendors morning bustle',
  'paris cafe terrace morning',
  'hong kong neon sign canyon',
  'istanbul grand bazaar crowd',
  'london fog evening street',
  'subway platform commuters motion blur',
  'street saxophone player lamplight',
  'lisbon tram climbing hills',
  'seoul alley signage dusk',
  'long exposure crosswalk trails',
  'iceland waterfall aurora backdrop',
  'dolomites alpenglow peaks',
  'slot canyon shaft of light',
  'scottish highlands rolling mist',
  'norwegian fjord glassy reflections',
  'patagonia granite towers sunrise',
  'lavender fields provence rows',
  'cherry blossom valley japan',
  'savanna acacia sunset silhouettes',
  'arctic icebergs calm sea',
  'rice terraces bali morning',
  'supercell thunderstorm open plains',
  'autumn forest fog path',
  'turquoise cove aerial view',
  'badlands moonlit badlands night',
  'alpine lake mirror reflection',
  'snow leopard intense gaze',
  'hummingbird frozen mid-flight macro',
  'wolf pack moving through snow',
  'owl hunting under moonlight',
  'red fox autumn undergrowth',
  'elephant herd dust golden light',
  'humpback whale breach splash',
  'scarlet macaw rainforest perch',
  'jellyfish drifting deep glow',
  'lion mane backlit savanna',
  'penguin colony antarctic ice',
  'koi pond ripple rings',
  'wild horses galloping surf',
  'chameleon macro skin detail',
  'brutalist concrete facade geometry',
  'gothic cathedral nave light shafts',
  'modern museum spiral atrium glass',
  'japanese temple moss garden',
  'islamic courtyard geometric tilework',
  'mid-century modern house dusk glass walls',
  'cathedral of light interior columns',
  'art deco hotel lobby brass',
  'cliffside monastery stone steps',
  'futuristic transit hub curves',
  'bamboo pavilion dappled shade',
  'grand library reading hall',
  'kodachrome 1970s road trip station wagon',
  'portra 400 soft pastel portrait',
  'cinestill 800t neon night halation',
  'polaroid instant snapshot memory',
  'ektachrome slide film landscape',
  'tri-x black and white street frame',
  'technicolor musical set vibrance',
  'super 8 summer backyard memory',
  'expired film light leaks dreamy',
  'velvia saturated coastal cliffs',
  'ilford hp5 grainy portrait',
  'cross-processed lomo color shift',
  'ballet dancer grand jete stage spotlight',
  'contemporary dance fabric mid-air',
  'flamenco skirts spinning seville',
  'hip-hop dancer freeze jump rooftop',
  'tango embrace dim ballroom',
  'breakdance windmill concrete plaza',
  'ballet rehearsal studio mirrors morning',
  'irish dance line hard shoes',
  'salsa club colored lights spin',
  'aerial silk performer theater',
  'sprinter exploding off starting blocks',
  'marathon runner empty streets dawn',
  'gymnast balance beam concentration',
  'swimmer underwater lane bubbles',
  'rock climber overhang chalk dust',
  'boxer heavy bag gym grit',
  'striker bicycle kick floodlights',
  'basketball dunk arena spotlights',
  'cyclist alpine descent speed',
  'surfer inside barrel wave',
  'skier powder spray backlight',
  'fencer lunge blade flash',
  'classic muscle car desert highway',
  'vintage race car circuit chicane',
  'retro-futurist concept car showroom',
  'motorcycle mountain pass night headlight',
  'steam train crossing stone viaduct',
  'sailing yacht open ocean heel',
  'bush plane alpine lake landing',
  'rally car gravel corner drift',
  'art deco streamliner locomotive',
  'vintage scooter cobblestone italian street',
  'off-road truck cresting dunes',
  'airship moored above cloud sea',
  'cozy cabin fireplace snowfall window',
  'mid-century living room plants sunlight',
  'parisian apartment tall windows herringbone',
  'industrial loft exposed brick steel',
  'japandi bedroom soft linen light',
  'grand hotel lobby chandelier marble',
  'bookstore rolling ladder paper aisles',
  'recording studio console warm lamps',
  'conservatory greenhouse wicker chairs',
  'art collector salon gallery wall',
  'scandinavian kitchen morning coffee light',
  'speakeasy bar amber bottles glow',
  'rustic sourdough crumb close-up',
  'ramen bowl steam dark backdrop',
  'espresso pour crema macro',
  'farmers market produce crates morning',
  'patisserie display macarons pastel',
  'brisket smoke low and slow',
  'omakase sushi plating minimal',
  'summer picnic spread orchard blanket',
  'melted chocolate pouring swirl',
  'citrus still life dutch masters style',
  'street tacos night grill flames',
  'honey dripping from comb backlit',
  'sumi-e mountain brush wash',
  'ink wash dragon coiling clouds',
  'pen crosshatch old city rooftops',
  'botanical ink study fern fronds',
  'octopus tentacle linework poster',
  'stormy sea woodblock waves',
  'samurai single brush stroke',
  'ravens ink splatter sky',
  'lighthouse etching crosshatched storm',
  'koi circling enso brush circle',
  'impressionist garden pond loose strokes',
  'baroque still life grapes pewter',
  'oil seascape crashing breakers palette knife',
  'impasto oil portrait thick strokes',
  'sunflower field oil bold palette',
  'venetian canal oil reflections',
  'pastoral sheep meadow oil painting',
  'romantic storm clouds oil sky',
  'flower market oil sketch morning',
  'harbor dusk oil warm windows',
  'watercolor misty mountain ranges',
  'loose watercolor florals bleeding washes',
  'watercolor rooftops rainy city',
  'watercolor whale drifting calm',
  'watercolor lemon branch kitchen art',
  'watercolor lighthouse windswept coast',
  'watercolor ballerina single-line wash',
  'watercolor hot air balloons sky',
  'watercolor deer forest clearing',
  'watercolor teapot morning still life',
  'anime style rooftop sunset city',
  'cel-shaded floating sky islands',
  'manga panel rain scene screentones',
  'whimsical countryside bus stop spirits',
  'school festival paper lanterns anime style',
  'mecha pilot cockpit anime style',
  'magical transformation sparkles ribbons',
  'anime ramen shop interior evening',
  'battle aura cliffside shonen energy',
  'petals on balcony shojo framing',
  'retro 90s anime arcade glow',
  'train window passing landscape anime style',
];

function slugify(query: string): string {
  return query
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const SMALL_WORDS = new Set(['and', 'of', 'the', 'with', 'for', 'in', 'on', 'at', 'from']);

function titleize(query: string): string {
  const words = query.split(' ');
  return words
    .map((word, index) => {
      if (index > 0 && SMALL_WORDS.has(word)) return word;
      return word
        .split('-')
        .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part))
        .join('-');
    })
    .join(' ');
}

const BLURB_TEMPLATES: readonly ((title: string, lower: string) => string)[] = [
  (title, lower) => `Browse a curated set of ${lower} images generated with ManifoldGen. Open any result in Studio to remix the prompt into your own image or video.`,
  (title, lower) => `${title}, rendered by ManifoldGen: a hand-picked gallery of AI-generated frames with full prompts you can copy, restyle, and animate.`,
  (_title, lower) => `Explore ${lower} through AI image generation. Every thumbnail links back to its prompt so you can recreate the look in ManifoldGen Studio.`,
  (_title, lower) => `An AI-generated ${lower} gallery curated from the public ManifoldGen explore feed. Click any frame to open the original prompt.`,
  (_title, lower) => `See how ManifoldGen interprets ${lower}. Each result keeps its prompt attached so you can iterate on lighting, mood, and composition.`,
  (_title, lower) => `AI-generated ${lower}, curated by the ManifoldGen team for prompt inspiration. Remix any frame into video or a fresh still inside Studio.`,
];

export const CURATED_SEARCH_PAGES: CuratedSearchPage[] = QUERIES.map((query, index) => {
  const title = titleize(query);
  return {
    slug: slugify(query),
    query,
    title,
    blurb: BLURB_TEMPLATES[index % BLURB_TEMPLATES.length](title, query.toLowerCase()),
  };
});
