export interface CuratedSearchPage {
  slug: string;
  query: string;
  title: string;
  blurb: string;
  familyIndex: number;
}

const LEGACY_SEARCH_QUERIES: readonly string[] = [
  'cinematic portrait dramatic lighting',
  'rembrandt lighting portrait',
  'rain-soaked neon portrait',
  'film grain close-up portrait',
  'freckles natural window light portrait',
  'black and white studio portrait',
  'moody window light portrait',
  'golden hour side profile portrait',
  'teal and orange cinematic portrait',
  'shallow depth of field portrait bokeh',
  'vintage hollywood glamour portrait',
  'chiaroscuro dramatic portrait',
  'editorial beauty portrait dewy skin',
  'anamorphic lens flare portrait',
  'candid laughter portrait warm tones',
  'film noir detective office',
  'film noir femme fatale silhouette',
  'rainy street film noir',
  'venetian blind shadow noir',
  'film noir cityscape night',
  'smoky jazz club noir',
  'trench coat alleyway noir',
  'high contrast monochrome noir street',
  'film noir interrogation room',
  'noir lighthouse storm',
  'golden hour field portrait',
  'golden hour city skyline',
  'golden hour beach waves',
  'golden hour mountain ridge',
  'golden hour wheat field',
  'golden hour desert dunes',
  'golden hour rooftop silhouette',
  'golden hour forest sun rays',
  'golden hour lakeside reflection',
  'golden hour hot air balloon',
  'cyberpunk street market rain',
  'cyberpunk megacity skyline',
  'cyberpunk samurai neon',
  'cyberpunk hacker den monitors',
  'cyberpunk android portrait',
  'neon-soaked alley cyberpunk',
  'cyberpunk flying taxi traffic',
  'cyberpunk noodle bar steam',
  'cyberpunk graffiti wall night',
  'cyberpunk courier bike chase',
  'cyberpunk underground club lights',
  'cyberpunk rooftop rain skyline',
  'elven archer misty forest',
  'fantasy knight armor battlefield',
  'sorceress casting glowing spell',
  'dwarven blacksmith forge sparks',
  'orc warband marching',
  'fantasy castle siege dawn',
  'dragon rider above clouds',
  'ranger with longbow pine woods',
  'battle mage lightning storm',
  'elf queen throne room',
  'paladin radiant sword',
  'necromancer tower moonlit',
  'barbarian warrior snowy peak',
  'fairy glade moonlight',
  'griffin rider sea cliffs',
  'wizard study ancient tomes',
  'enchanted forest path lanterns',
  'bustling fantasy tavern market',
  'space station orbiting ringed planet',
  'alien jungle explorer expedition',
  'mars colony dome habitat',
  'starship bridge viewport stars',
  'derelict spaceship corridor',
  'mecha hangar maintenance crew',
  'terraformed moon base panorama',
  'wormhole jump starfield stretch',
  'alien bazaar crowded stalls',
  'cryosleep pod bay glow',
  'orbital elevator rising storm',
  'exoplanet twin sunrise landscape',
  'robot gardener greenhouse rows',
  'deep space nebula vista',
  'editorial fashion studio shoot',
  'evening gown red carpet moment',
  'haute couture runway walk',
  'avant-garde fashion sculpture silhouette',
  'fashion editorial desert dunes',
  'street style fashion week crowd',
  'monochrome fashion editorial wind machine',
  'silk dress flowing studio motion',
  'fashion editorial rooftop dusk',
  'bold color blocking fashion editorial',
  'vintage 1950s fashion editorial',
  'leather jacket urban editorial night',
  'tulle dress mid-motion editorial',
  'minimalist fashion white backdrop',
  'tokyo crossing at night crowd',
  'new york rainy umbrellas crosswalk',
  'market vendors morning bustle',
  'paris cafe terrace morning',
  'hong kong neon sign canyon',
  'istanbul grand bazaar crowd',
  'london fog evening street',
  'subway platform commuters motion blur',
  'street saxophone player lamplight',
  'lisbon tram climbing hills',
  'seoul alley signage dusk',
  'long exposure crosswalk trails',
  'iceland waterfall aurora backdrop',
  'dolomites alpenglow peaks',
  'slot canyon shaft of light',
  'scottish highlands rolling mist',
  'norwegian fjord glassy reflections',
  'patagonia granite towers sunrise',
  'lavender fields provence rows',
  'cherry blossom valley japan',
  'savanna acacia sunset silhouettes',
  'arctic icebergs calm sea',
  'rice terraces bali morning',
  'supercell thunderstorm open plains',
  'autumn forest fog path',
  'turquoise cove aerial view',
  'badlands moonlit badlands night',
  'alpine lake mirror reflection',
  'snow leopard intense gaze',
  'hummingbird frozen mid-flight macro',
  'wolf pack moving through snow',
  'owl hunting under moonlight',
  'red fox autumn undergrowth',
  'elephant herd dust golden light',
  'humpback whale breach splash',
  'scarlet macaw rainforest perch',
  'jellyfish drifting deep glow',
  'lion mane backlit savanna',
  'penguin colony antarctic ice',
  'koi pond ripple rings',
  'wild horses galloping surf',
  'chameleon macro skin detail',
  'brutalist concrete facade geometry',
  'gothic cathedral nave light shafts',
  'modern museum spiral atrium glass',
  'japanese temple moss garden',
  'islamic courtyard geometric tilework',
  'mid-century modern house dusk glass walls',
  'cathedral of light interior columns',
  'art deco hotel lobby brass',
  'cliffside monastery stone steps',
  'futuristic transit hub curves',
  'bamboo pavilion dappled shade',
  'grand library reading hall',
  'kodachrome 1970s road trip station wagon',
  'portra 400 soft pastel portrait',
  'cinestill 800t neon night halation',
  'polaroid instant snapshot memory',
  'ektachrome slide film landscape',
  'tri-x black and white street frame',
  'technicolor musical set vibrance',
  'super 8 summer backyard memory',
  'expired film light leaks dreamy',
  'velvia saturated coastal cliffs',
  'ilford hp5 grainy portrait',
  'cross-processed lomo color shift',
  'ballet dancer grand jete stage spotlight',
  'contemporary dance fabric mid-air',
  'flamenco skirts spinning seville',
  'hip-hop dancer freeze jump rooftop',
  'tango embrace dim ballroom',
  'breakdance windmill concrete plaza',
  'ballet rehearsal studio mirrors morning',
  'irish dance line hard shoes',
  'salsa club colored lights spin',
  'aerial silk performer theater',
  'sprinter exploding off starting blocks',
  'marathon runner empty streets dawn',
  'gymnast balance beam concentration',
  'swimmer underwater lane bubbles',
  'rock climber overhang chalk dust',
  'boxer heavy bag gym grit',
  'striker bicycle kick floodlights',
  'basketball dunk arena spotlights',
  'cyclist alpine descent speed',
  'surfer inside barrel wave',
  'skier powder spray backlight',
  'fencer lunge blade flash',
  'classic muscle car desert highway',
  'vintage race car circuit chicane',
  'retro-futurist concept car showroom',
  'motorcycle mountain pass night headlight',
  'steam train crossing stone viaduct',
  'sailing yacht open ocean heel',
  'bush plane alpine lake landing',
  'rally car gravel corner drift',
  'art deco streamliner locomotive',
  'vintage scooter cobblestone italian street',
  'off-road truck cresting dunes',
  'airship moored above cloud sea',
  'cozy cabin fireplace snowfall window',
  'mid-century living room plants sunlight',
  'parisian apartment tall windows herringbone',
  'industrial loft exposed brick steel',
  'japandi bedroom soft linen light',
  'grand hotel lobby chandelier marble',
  'bookstore rolling ladder paper aisles',
  'recording studio console warm lamps',
  'conservatory greenhouse wicker chairs',
  'art collector salon gallery wall',
  'scandinavian kitchen morning coffee light',
  'speakeasy bar amber bottles glow',
  'rustic sourdough crumb close-up',
  'citrus still life dutch masters style',
  'street tacos night grill flames',
  'honey dripping from comb backlit',
  'sumi-e mountain brush wash',
  'ink wash dragon coiling clouds',
  'pen crosshatch old city rooftops',
  'botanical ink study fern fronds',
  'octopus tentacle linework poster',
  'stormy sea woodblock waves',
  'samurai single brush stroke',
  'ravens ink splatter sky',
  'lighthouse etching crosshatched storm',
  'koi circling enso brush circle',
  'impressionist garden pond loose strokes',
  'baroque still life grapes pewter',
  'oil seascape crashing breakers palette knife',
  'impasto oil portrait thick strokes',
  'sunflower field oil bold palette',
  'venetian canal oil reflections',
  'pastoral sheep meadow oil painting',
  'romantic storm clouds oil sky',
  'flower market oil sketch morning',
  'harbor dusk oil warm windows',
  'watercolor misty mountain ranges',
  'loose watercolor florals bleeding washes',
  'watercolor rooftops rainy city',
  'watercolor whale drifting calm',
  'watercolor lemon branch kitchen art',
  'watercolor lighthouse windswept coast',
  'watercolor ballerina single-line wash',
  'watercolor hot air balloons sky',
  'watercolor deer forest clearing',
  'watercolor teapot morning still life',
  'anime style rooftop sunset city',
  'cel-shaded floating sky islands',
  'manga panel rain scene screentones',
  'whimsical countryside bus stop spirits',
  'school festival paper lanterns anime style',
  'mecha pilot cockpit anime style',
  'magical transformation sparkles ribbons',
  'anime ramen shop interior evening',
  'battle aura cliffside shonen energy',
  'petals on balcony shojo framing',
  'retro 90s anime arcade glow',
  'train window passing landscape anime style',
];

const FOOD_SEARCH_QUERY_GROUPS: readonly (readonly string[])[] = [
// Ramen & noodle bowls
[
  'ramen bowl steam dark backdrop',
  'kotteri rich ramen chashu pork izakaya booth',
  'assari clear ramen izakaya booth overhead flat lay',
  'abura soba noodles candlelit shadows',
  'shoyu ramen candlelit shadows',
  'tsukemen dipping noodles narutomaki overhead flat lay',
  'shoyu ramen wood ear mushrooms midnight diner counter',
  'shio ramen chashu pork warm pendant light',
  'tantanmen noodles neon sign reflections',
  'noodle strainer toss backlit steam',
  'yuzu shio ramen dark wooden table backlit steam',
  'miso ramen neon sign reflections',
  'black garlic ramen paper lantern glow candlelit shadows',
  'shio ramen backlit steam',
  'kotteri rich ramen lantern street stall backlit steam',
  'shoyu ramen open kitchen steam backlit steam',
  'kotteri rich ramen chashu pork steamed-up glass',
  'curry ramen warm pendant light',
  'tonkotsu ramen soft egg ajitama noodle bar counter',
  'black garlic ramen izakaya booth candlelit shadows',
  'tsukemen dipping noodles nori overhead flat lay',
  'shio ramen noodle bar counter neon sign reflections',
  'assari clear ramen chashu pork izakaya booth',
  'dipping tsukemen ramen rain-streaked window seat backlit steam',
  'yuzu shio ramen narutomaki warm pendant light',
  'noodle strainer toss wontons overhead flat lay',
  'spicy tantanmen ramen chashu pork brass rail counter',
  'tsukemen dipping noodles neon sign reflections',
  'shio ramen candlelit shadows',
  'yuzu shio ramen scallion steamed-up glass',
  'shio ramen narutomaki moody dark backdrop',
  'noodle strainer toss candlelit shadows',
  'yuzu shio ramen backlit steam',
  'tonkotsu ramen narutomaki backlit steam',
  'ramen egg halves scallion moody dark backdrop',
  'spicy tantanmen ramen rain-streaked window seat backlit steam',
  'shoyu ramen overhead flat lay',
  'miso ramen bamboo menma candlelit shadows',
  'tantanmen noodles overhead flat lay',
  'yuzu shio ramen overhead flat lay',
  'shio ramen open kitchen steam candlelit shadows',
  'shoyu ramen warm pendant light',
  'shio ramen wood ear mushrooms overhead flat lay',
  'ramen bowl bamboo menma overhead flat lay',
  'assari clear ramen izakaya booth warm pendant light',
  'tonkotsu ramen midnight diner counter moody dark backdrop',
  'miso ramen paper lantern glow candlelit shadows',
  'yuzu shio ramen wontons brass rail counter',
  'shio ramen overhead flat lay',
  'noodle pull chopstick lift neon sign reflections',
  'miso ramen open kitchen steam candlelit shadows',
  'shio ramen chili oil swirl dark wooden table',
  'ramen egg halves scallion candlelit shadows',
  'curry ramen lantern street stall moody dark backdrop',
  'pork bone broth simmer overhead flat lay',
  'ramen bowl candlelit shadows',
  'ramen bowl soft egg and chashu backlit steam',
  'kotteri rich ramen wontons izakaya booth',
  'dipping tsukemen ramen izakaya booth warm pendant light',
  'ramen egg halves nori overhead flat lay',
  'shio ramen pork belly slab open kitchen steam',
  'tantanmen noodles nori warm pendant light',
  'tonkotsu ramen soft egg and chashu candlelit shadows',
  'shio ramen soft egg and chashu izakaya booth',
  'noodle strainer toss sweetcorn butter moody dark backdrop',
  'brothless abura soba ramen nori midnight diner counter',
  'ramen egg halves backlit steam',
  'tantanmen noodles warm pendant light',
  'tonkotsu ramen wood ear mushrooms moody dark backdrop',
  'tsukemen dipping noodles scallion moody dark backdrop',
  'yuzu shio ramen wontons paper lantern glow',
  'pork bone broth simmer backlit steam',
  'shio ramen scallion paper lantern glow',
  'noodle pull chopstick lift moody dark backdrop',
  'abura soba noodles overhead flat lay',
  'yuzu shio ramen moody dark backdrop',
  'shoyu ramen wood ear mushrooms paper lantern glow',
  'ramen egg halves moody dark backdrop',
  'black garlic ramen soft egg ajitama candlelit shadows',
  'chashu slice fan neon sign reflections',
  'tonkotsu ramen soft egg ajitama lantern street stall',
  'yuzu shio ramen candlelit shadows',
  'tonkotsu ramen garlic chips brass rail counter',
  'pork bone broth simmer scallion moody dark backdrop',
  'tsukemen dipping noodles sesame backlit steam',
  'kotteri rich ramen bamboo menma noodle bar counter',
  'yuzu shio ramen steamed-up glass backlit steam',
  'noodle pull chopstick lift wontons overhead flat lay',
  'shoyu ramen bamboo menma moody dark backdrop',
  'curry ramen dark wooden table warm pendant light',
  'shio ramen sweetcorn butter rain-streaked window seat',
  'curry ramen garlic chips candlelit shadows',
  'ramen bowl overhead flat lay',
  'shio ramen dark wooden table moody dark backdrop',
  'tonkotsu ramen candlelit shadows',
  'black garlic ramen backlit steam',
  'shoyu ramen chili oil swirl overhead flat lay',
  'shio ramen sweetcorn butter lantern street stall',
  'curry ramen bamboo menma izakaya booth',
  'shio ramen scallion steamed-up glass',
  'shoyu ramen wontons neon sign reflections',
  'ramen bowl warm pendant light',
  'chashu slice fan moody dark backdrop',
  'miso ramen backlit steam',
  'curry ramen izakaya booth moody dark backdrop',
  'curry ramen bamboo menma steamed-up glass',
  'abura soba noodles warm pendant light',
  'curry ramen wontons rain-streaked window seat',
  'noodle pull chopstick lift warm pendant light',
  'dipping tsukemen ramen garlic chips lantern street stall',
  'ramen egg halves narutomaki backlit steam',
  'miso ramen midnight diner counter overhead flat lay',
  'shoyu ramen moody dark backdrop',
  'curry ramen sweetcorn butter lantern street stall',
  'curry ramen garlic chips moody dark backdrop',
  'ramen bowl sesame neon sign reflections',
  'noodle pull chopstick lift overhead flat lay',
  'miso ramen narutomaki overhead flat lay',
  'noodle strainer toss moody dark backdrop',
  'black garlic ramen warm pendant light',
  'abura soba noodles moody dark backdrop',
  'spicy tantanmen ramen narutomaki lantern street stall',
  'assari clear ramen bamboo menma midnight diner counter',
  'pork bone broth simmer wontons candlelit shadows',
  'dipping tsukemen ramen garlic chips steamed-up glass',
  'assari clear ramen narutomaki lantern street stall',
  'shio ramen izakaya booth candlelit shadows',
  'curry ramen pork belly slab noodle bar counter',
  'pork bone broth simmer warm pendant light',
  'ramen egg halves garlic chips backlit steam',
  'shio ramen garlic chips rain-streaked window seat',
  'shoyu ramen open kitchen steam moody dark backdrop',
  'shoyu ramen bamboo menma izakaya booth',
  'assari clear ramen steamed-up glass moody dark backdrop',
  'kotteri rich ramen soft egg ajitama izakaya booth',
  'tonkotsu ramen steamed-up glass candlelit shadows',
  'tonkotsu ramen izakaya booth candlelit shadows',
  'brothless abura soba ramen wontons lantern street stall',
  'yuzu shio ramen warm pendant light',
  'shio ramen warm pendant light',
],
// Espresso & coffee
[
  'espresso pour crema macro',
  'lungo cup warm morning glow',
  'macchiato crema tiger stripes',
  'flat white puck knock out',
  'cortado first drip extraction',
  'cappuccino cup overhead flat lay',
  'espresso tonic milk pour rosetta',
  'espresso puck knock out moody low key',
  'single origin espresso linen-draped counter moody low key',
  'lungo cup high gloss reflection',
  'doppio espresso linen-draped counter overhead flat lay',
  'cappuccino bean grind cascade',
  'macchiato morning window light crema macro',
  'lungo cup crema macro',
  'ristretto cup high gloss reflection',
  'espresso tonic puck knock out',
  'espresso tonic linen-draped counter moody low key',
  'espresso bottomless portafilter drip overhead flat lay',
  'espresso cup warming rack warm morning glow',
  'doppio espresso puck knock out',
  'flat white steam wand hiss',
  'espresso tonic copper machine chrome warm morning glow',
  'doppio espresso cup moody low key',
  'espresso puck knock out warm morning glow',
  'flat white cup crema macro',
  'cappuccino cup high gloss reflection',
  'espresso tonic cup overhead flat lay',
  'espresso crema tiger stripes high gloss reflection',
  'espresso cup warming rack moody low key',
  'ristretto crema tiger stripes',
  'macchiato bean grind cascade',
  'affogato cup high gloss reflection',
  'flat white bean grind cascade',
  'espresso bottomless portafilter drip high gloss reflection',
  'lungo cup warming rack',
  'macchiato milk pour rosetta',
  'ristretto bean grind cascade',
  'doppio espresso cup overhead flat lay',
  'espresso bottomless portafilter drip crema macro',
  'lungo cup overhead flat lay',
  'cappuccino first drip extraction',
  'affogato cup crema macro',
  'affogato first drip extraction',
  'single origin espresso cup high gloss reflection',
  'espresso cup warming rack high gloss reflection',
  'cappuccino matte grinder side moody low key',
  'affogato cup shallow depth of field bokeh',
  'cortado crema tiger stripes',
  'affogato bean grind cascade',
  'espresso tonic tiled bistro top crema macro',
  'cortado copper machine chrome warm morning glow',
  'espresso tonic bottomless portafilter drip',
  'cappuccino crema tiger stripes',
  'espresso bean grind cascade overhead flat lay',
  'single origin espresso cup crema macro',
  'macchiato cup warm morning glow',
  'affogato tiled bistro top high gloss reflection',
  'cappuccino steam wand hiss',
  'espresso steam wand hiss warm morning glow',
  'espresso tonic cup crema macro',
  'espresso crema tiger stripes warm morning glow',
  'ristretto cup warming rack',
  'doppio espresso cup warming rack',
  'macchiato dark wood counter crema macro',
  'lungo cup shallow depth of field bokeh',
  'espresso first drip extraction high gloss reflection',
  'espresso steam wand hiss moody low key',
  'espresso tonic first drip extraction',
  'cappuccino cup warming rack',
  'doppio espresso linen-draped counter moody low key',
  'macchiato steam wand hiss',
  'espresso first drip extraction overhead flat lay',
  'ristretto milk pour rosetta',
  'espresso first drip extraction warm morning glow',
  'ristretto cup warm morning glow',
  'espresso bean grind cascade high gloss reflection',
  'cappuccino cup warm morning glow',
  'single origin espresso puck knock out',
  'doppio espresso cup shallow depth of field bokeh',
  'cortado matte grinder side moody low key',
  'flat white dark wood counter moody low key',
  'single origin espresso steam wand hiss',
  'flat white cup warm morning glow',
  'macchiato cup high gloss reflection',
  'espresso puck knock out overhead flat lay',
  'espresso tonic cup warming rack',
  'espresso cup warming rack overhead flat lay',
  'single origin espresso bottomless portafilter drip',
  'espresso bottomless portafilter drip warm morning glow',
  'espresso puck knock out crema macro',
  'espresso first drip extraction crema macro',
  'cortado tiled bistro top warm morning glow',
  'flat white cup overhead flat lay',
  'cortado linen-draped counter shallow depth of field bokeh',
  'cortado bottomless portafilter drip',
  'flat white sugar-dusted marble moody low key',
  'espresso milk pour rosetta moody low key',
  'ristretto first drip extraction',
  'ristretto marble cafe bar moody low key',
  'flat white cup moody low key',
  'affogato marble cafe bar moody low key',
  'ristretto dark wood counter warm morning glow',
  'cortado cup moody low key',
  'cortado steam wand hiss',
  'cappuccino cup moody low key',
  'espresso crema tiger stripes moody low key',
  'ristretto cup overhead flat lay',
  'espresso tonic bean grind cascade',
  'espresso tonic marble cafe bar moody low key',
  'flat white cup shallow depth of field bokeh',
  'flat white milk pour rosetta',
  'single origin espresso cup overhead flat lay',
  'cappuccino tiled bistro top overhead flat lay',
  'ristretto morning window light crema macro',
  'doppio espresso bottomless portafilter drip',
  'cortado marble cafe bar crema macro',
  'espresso tonic marble cafe bar crema macro',
  'flat white cup high gloss reflection',
  'doppio espresso steam wand hiss',
  'ristretto linen-draped counter moody low key',
  'doppio espresso milk pour rosetta',
  'cortado cup warm morning glow',
  'cappuccino bottomless portafilter drip',
  'cortado morning window light crema macro',
  'flat white marble cafe bar overhead flat lay',
  'cappuccino milk pour rosetta',
  'espresso tonic cup warm morning glow',
  'ristretto cup shallow depth of field bokeh',
  'ristretto cup crema macro',
  'espresso tonic cup moody low key',
  'espresso milk pour rosetta overhead flat lay',
  'macchiato cup crema macro',
  'cappuccino linen-draped counter high gloss reflection',
  'single origin espresso milk pour rosetta',
  'flat white morning window light warm morning glow',
  'espresso first drip extraction moody low key',
  'espresso bottomless portafilter drip moody low key',
  'affogato cup moody low key',
  'ristretto cup moody low key',
  'espresso puck knock out high gloss reflection',
],
// Farmers market produce
[
  'farmers market produce crates morning',
  'cabbage heads long shadow morning',
  'melon halves dew droplets',
  'morning stall row golden hour glow',
  'pepper medley cobblestone square',
  'squash stacks truck tailgate display',
  'root vegetable piles truck tailgate display',
  'fig punnets crates hanging scale soft overcast light',
  'pepper medley hanging scale',
  'farmers market crates long shadow morning',
  'hanging scale golden hour glow',
  'cabbage heads early morning light',
  'cabbage heads cobblestone square',
  'wooden crate display golden hour glow',
  'citrus crates crates string canopy shade dew droplets',
  'berry pints crates farmers market crates dew droplets',
  'mushroom baskets crates woven baskets long shadow morning',
  'grape clusters crates woven baskets dew droplets',
  'egg cartons woven baskets',
  'corn husks cobblestone square',
  'citrus crates hanging scale',
  'melon halves long shadow morning',
  'melon halves soft overcast light',
  'grape clusters morning stall row',
  'pepper medley canvas awning stall',
  'cobblestone square early morning light',
  'fig punnets dew droplets',
  'egg cartons dappled canopy light',
  'morning stall row dew droplets',
  'squash stacks long shadow morning',
  'root vegetable piles long shadow morning',
  'grape clusters truck tailgate display',
  'stone fruit crates dew droplets',
  'canvas awning stall early morning light',
  'stone fruit crates farmers market crates',
  'citrus crates morning stall row',
  'cobblestone square soft overcast light',
  'grape clusters cobblestone square',
  'egg cartons crates cobblestone square dappled canopy light',
  'flower bouquets farmers market crates',
  'root vegetable piles golden hour glow',
  'farmers market crates dew droplets',
  'grape clusters string canopy shade',
  'morning stall row early morning light',
  'corn husks early morning light',
  'root vegetable piles cobblestone square',
  'melon halves wooden crate display',
  'grape clusters hanging scale',
  'canvas awning stall golden hour glow',
  'berry pints hanging scale',
  'string canopy shade soft overcast light',
  'berry pints early morning light',
  'corn husks dappled canopy light',
  'flower bouquets crates truck tailgate display dew droplets',
  'kraft paper bags dew droplets',
  'woven baskets long shadow morning',
  'flower bouquets long shadow morning',
  'flower bouquets string canopy shade',
  'corn husks crates woven baskets long shadow morning',
  'stone fruit crates golden hour glow',
  'radish bunches dappled canopy light',
  'wooden crate display early morning light',
  'egg cartons morning stall row',
  'cobblestone square golden hour glow',
  'squash stacks dew droplets',
  'truck tailgate display long shadow morning',
  'farmers market crates dappled canopy light',
  'mushroom baskets cobblestone square',
  'citrus crates golden hour glow',
  'morning stall row long shadow morning',
  'grape clusters farmers market crates',
  'heirloom tomatoes dew droplets',
  'leafy green bundles hanging scale',
  'berry pints cobblestone square',
  'stone fruit crates wooden crate display',
  'radish bunches dew droplets',
  'kraft paper bags long shadow morning',
  'hanging scale soft overcast light',
  'wooden crate display long shadow morning',
  'hanging scale dappled canopy light',
  'root vegetable piles wooden crate display',
  'grape clusters early morning light',
  'radish bunches woven baskets',
  'leafy green bundles early morning light',
  'kraft paper bags early morning light',
  'squash stacks crates truck tailgate display dew droplets',
  'canvas awning stall soft overcast light',
  'cabbage heads truck tailgate display',
  'canvas awning stall dappled canopy light',
  'stone fruit crates dappled canopy light',
  'herb bunches morning stall row',
  'herb bunches dew droplets',
  'hanging scale early morning light',
  'root vegetable piles early morning light',
  'squash stacks farmers market crates',
  'root vegetable piles morning stall row',
  'cabbage heads canvas awning stall',
  'herb bunches farmers market crates',
  'herb bunches long shadow morning',
  'wooden crate display soft overcast light',
  'corn husks dew droplets',
  'pepper medley kraft paper bags',
  'cabbage heads dew droplets',
  'pepper medley farmers market crates',
  'fig punnets long shadow morning',
  'melon halves canvas awning stall',
  'farmers market crates soft overcast light',
  'berry pints canvas awning stall',
  'wooden crate display dappled canopy light',
  'egg cartons crates wooden crate display dew droplets',
  'mushroom baskets kraft paper bags',
  'mushroom baskets long shadow morning',
  'mushroom baskets canvas awning stall',
  'corn husks farmers market crates',
  'grape clusters kraft paper bags',
  'corn husks crates hanging scale golden hour glow',
  'egg cartons wooden crate display',
  'heirloom tomatoes canvas awning stall',
  'cobblestone square dappled canopy light',
  'herb bunches crates truck tailgate display dew droplets',
  'herb bunches kraft paper bags',
  'pepper medley golden hour glow',
  'egg cartons crates woven baskets early morning light',
  'corn husks canvas awning stall',
  'flower bouquets crates farmers market crates dew droplets',
  'root vegetable piles kraft paper bags',
  'morning stall row soft overcast light',
  'woven baskets soft overcast light',
  'truck tailgate display golden hour glow',
  'citrus crates woven baskets',
  'radish bunches morning stall row',
  'farmers market crates early morning light',
  'flower bouquets morning stall row',
  'citrus crates crates hanging scale dappled canopy light',
  'radish bunches crates cobblestone square early morning light',
  'egg cartons early morning light',
  'flower bouquets soft overcast light',
  'corn husks crates hanging scale soft overcast light',
  'stone fruit crates morning stall row',
  'egg cartons soft overcast light',
],
// Patisserie & pastry
[
  'patisserie display macarons pastel',
  'madeleines display bakery morning glow',
  'raspberry tartlets tiered pastry stand',
  'mirror glaze entremet pastel color palette',
  'pastel backdrop soft daylight',
  'marble counter bright airy styling',
  'macaron tower display bright airy styling',
  'choux buns glass dome cloche',
  'glossy fruit tarts bakery window shelf',
  'macaron tower soft daylight',
  'ribboned gift box soft daylight',
  'glossy fruit tarts bakery morning glow',
  'caneles doily lined tray',
  'praline paris-brest tongs and tissue',
  'pistachio religieuse doily lined tray',
  'opera cake layers gentle gradient backdrop',
  'danish pastries ribboned gift box',
  'lemon meringue tart marble counter',
  'caneles display soft daylight',
  'almond croissants bakery window shelf',
  'chocolate bonbons display bright airy styling',
  'lemon meringue tart bright airy styling',
  'lemon meringue tart bakery morning glow',
  'macaron tower pastel color palette',
  'choux buns display gentle gradient backdrop',
  'madeleines bright airy styling',
  'glass dome cloche bakery morning glow',
  'glossy fruit tarts ribboned gift box',
  'laminated croissants display soft daylight',
  'laminated croissants display gentle gradient backdrop',
  'bakery window shelf bakery morning glow',
  'pistachio religieuse soft daylight',
  'glass dome cloche gentle gradient backdrop',
  'opera cake layers display soft daylight',
  'praline paris-brest tiered pastry stand',
  'caneles bakery morning glow',
  'madeleines bakery morning glow',
  'raspberry tartlets gentle gradient backdrop',
  'danish pastries display bright airy styling',
  'glossy fruit tarts pastel color palette',
  'praline paris-brest ribboned gift box',
  'ribboned gift box bright airy styling',
  'almond croissants pastel color palette',
  'choux buns soft daylight',
  'madeleines ribboned gift box',
  'pistachio religieuse display soft daylight',
  'pastel macarons display soft daylight',
  'raspberry tartlets display gentle gradient backdrop',
  'pistachio religieuse gentle gradient backdrop',
  'mille-feuille slices soft daylight',
  'pastel macarons bakery window shelf',
  'pastel macarons pastel backdrop',
  'almond croissants soft daylight',
  'pastel macarons soft daylight',
  'madeleines tiered pastry stand',
  'glossy fruit tarts bright airy styling',
  'mirror glaze entremet display bright airy styling',
  'marble counter pastel color palette',
  'mille-feuille slices display pastel color palette',
  'praline paris-brest glass dome cloche',
  'mille-feuille slices tongs and tissue',
  'pastel macarons display gentle gradient backdrop',
  'macaron tower bakery morning glow',
  'tongs and tissue soft daylight',
  'tongs and tissue pastel color palette',
  'mille-feuille slices glass dome cloche',
  'praline paris-brest display soft daylight',
  'choux buns display bakery morning glow',
  'tongs and tissue bright airy styling',
  'choux buns display soft daylight',
  'patisserie display case soft daylight',
  'madeleines display gentle gradient backdrop',
  'glossy fruit tarts pastel backdrop',
  'marble counter gentle gradient backdrop',
  'caneles tongs and tissue',
  'patisserie display case pastel color palette',
  'tongs and tissue gentle gradient backdrop',
  'doily lined tray bakery morning glow',
  'chocolate bonbons gentle gradient backdrop',
  'caneles marble counter',
  'ribboned gift box pastel color palette',
  'praline paris-brest display gentle gradient backdrop',
  'almond croissants gentle gradient backdrop',
  'almond croissants display bright airy styling',
  'chocolate bonbons doily lined tray',
  'pastel macarons bright airy styling',
  'tiered pastry stand soft daylight',
  'salted caramel eclairs display soft daylight',
  'lemon meringue tart tongs and tissue',
  'tiered pastry stand pastel color palette',
  'patisserie display case bright airy styling',
  'marble counter bakery morning glow',
  'lemon meringue tart glass dome cloche',
  'salted caramel eclairs doily lined tray',
  'caneles display bakery morning glow',
  'mirror glaze entremet display bakery morning glow',
  'marble counter soft daylight',
  'pastel backdrop gentle gradient backdrop',
  'praline paris-brest bakery morning glow',
  'madeleines display pastel color palette',
  'danish pastries tiered pastry stand',
  'pistachio religieuse pastel color palette',
  'choux buns display bright airy styling',
  'pastel macarons ribboned gift box',
  'mirror glaze entremet display pastel color palette',
  'danish pastries tongs and tissue',
  'opera cake layers glass dome cloche',
  'opera cake layers pastel color palette',
  'lemon meringue tart display bright airy styling',
  'choux buns bakery morning glow',
  'choux buns ribboned gift box',
  'chocolate bonbons bakery window shelf',
  'salted caramel eclairs gentle gradient backdrop',
  'madeleines soft daylight',
  'pistachio religieuse tongs and tissue',
  'raspberry tartlets display bakery morning glow',
  'pastel macarons display bakery morning glow',
  'danish pastries pastel color palette',
  'ribboned gift box bakery morning glow',
  'glass dome cloche bright airy styling',
  'pastel macarons gentle gradient backdrop',
  'raspberry tartlets display pastel color palette',
  'mille-feuille slices tiered pastry stand',
  'laminated croissants pastel color palette',
  'macaron tower gentle gradient backdrop',
  'danish pastries bakery morning glow',
  'mille-feuille slices marble counter',
  'opera cake layers tiered pastry stand',
  'chocolate bonbons soft daylight',
  'macaron tower doily lined tray',
  'choux buns display pastel color palette',
  'glossy fruit tarts glass dome cloche',
  'pistachio religieuse bright airy styling',
  'glossy fruit tarts display bright airy styling',
  'praline paris-brest bright airy styling',
  'pastel macarons tongs and tissue',
  'salted caramel eclairs bakery morning glow',
  'danish pastries display pastel color palette',
  'bakery window shelf pastel color palette',
  'lemon meringue tart display gentle gradient backdrop',
],
// Barbecue & smoke
[
  'brisket smoke low and slow',
  'smoked sausage links rub crusted bark',
  'burnt ends sliced butcher shop case amber hour',
  'smoked chuck roast picnic table spread',
  'smoked brisket steel prep counter',
  'smoked brisket pitmaster cutting board',
  'whole packer brisket chimney smoke plume',
  'pulled pork shoulder rub crusted bark',
  'barbecue post-oak log pile steel prep counter',
  'baby back ribs pitmaster cutting board',
  'barbecue offset smoker firebox steel prep counter',
  'smoked brisket sliced picnic table spread amber hour',
  'brisket bark slices post-oak log pile',
  'baby back ribs rub crusted bark',
  'barbecue butcher paper unwrap steel prep counter',
  'barbecue post-oak log pile pitmaster cutting board',
  'pulled pork shoulder butcher shop case',
  'pork belly burnt ends rub crusted bark',
  'brisket bark slices offset smoker firebox',
  'barbecue post-oak log pile tailgate rig',
  'barbecue offset smoker firebox tailgate rig',
  'smoked sausage links chimney smoke plume',
  'baby back ribs picnic table spread',
  'beef ribs offset smoker firebox',
  'beef ribs pitmaster cutting board',
  'smoked sausage links sliced tailgate rig amber hour',
  'smoked brisket low and slow smokeout',
  'whole packer brisket smokehouse dusk',
  'barbecue rendered fat cap pitmaster cutting board',
  'smoked chuck roast post-oak log pile',
  'smoked brisket tailgate rig',
  'barbecue chimney smoke plume smokehouse dusk',
  'whole packer brisket rendered fat cap',
  'burnt ends steel prep counter',
  'brisket bark slices smokehouse dusk',
  'baby back ribs steel prep counter',
  'smoked brisket slice board resting juices',
  'smoked chuck roast steel prep counter',
  'barbecue rub crusted bark picnic table spread',
  'whole packer brisket sliced smokehouse dusk amber hour',
  'baby back ribs sliced tailgate rig ember glow',
  'brisket bark slices pit room embers',
  'pulled pork shoulder chimney smoke plume',
  'brisket bark slices smoke ring reveal',
  'whole packer brisket tailgate rig',
  'baby back ribs smokehouse dusk',
  'barbecue offset smoker firebox low and slow smokeout',
  'beef ribs picnic table spread',
  'burnt ends low and slow smokeout',
  'pulled pork shoulder tailgate rig',
  'smoked sausage links offset smoker firebox',
  'barbecue rub crusted bark low and slow smokeout',
  'brisket bark slices sliced tailgate rig backlit smoke',
  'burnt ends rub crusted bark',
  'burnt ends rendered fat cap',
  'barbecue chimney smoke plume pitmaster cutting board',
  'smoked chuck roast sliced smokehouse dusk ember glow',
  'brisket bark slices slice board resting juices',
  'barbecue slice board resting juices steel prep counter',
  'barbecue rub crusted bark pitmaster cutting board',
  'pork belly burnt ends smokehouse dusk',
  'baby back ribs butcher shop case',
  'smoked sausage links pitmaster cutting board',
  'beef ribs low and slow smokeout',
  'whole packer brisket pitmaster cutting board',
  'barbecue bbq sauce glaze butcher shop case',
  'pork belly burnt ends pitmaster cutting board',
  'barbecue rendered fat cap picnic table spread',
  'beef ribs bbq sauce glaze',
  'barbecue smoke ring reveal smokehouse dusk',
  'burnt ends picnic table spread',
  'pork belly burnt ends smoke ring reveal',
  'whole packer brisket rub crusted bark',
  'barbecue smoke ring reveal pitmaster cutting board',
  'smoked brisket offset smoker firebox',
  'pork belly burnt ends rendered fat cap',
  'brisket bark slices picnic table spread',
  'smoked sausage links tailgate rig',
  'smoked sausage links post-oak log pile',
  'beef ribs butcher paper unwrap',
  'smoked brisket sliced steel prep counter ember glow',
  'smoked chuck roast bbq sauce glaze',
  'barbecue post-oak log pile picnic table spread',
  'smoked brisket pit room embers',
  'smoked brisket picnic table spread',
  'smoked brisket butcher paper unwrap',
  'pulled pork shoulder low and slow smokeout',
  'smoked chuck roast smoke ring reveal',
  'burnt ends sliced smokehouse dusk backlit smoke',
  'whole packer brisket smoke ring reveal',
  'barbecue bbq sauce glaze low and slow smokeout',
  'barbecue slice board resting juices butcher shop case',
  'burnt ends sliced tailgate rig ember glow',
  'pulled pork shoulder rendered fat cap',
  'burnt ends smokehouse dusk',
  'barbecue offset smoker firebox pitmaster cutting board',
  'baby back ribs low and slow smokeout',
  'burnt ends chimney smoke plume',
  'pork belly burnt ends butcher paper unwrap',
  'smoked brisket butcher shop case',
  'smoked chuck roast butcher shop case',
  'burnt ends sliced pitmaster cutting board backlit smoke',
  'barbecue pit room embers steel prep counter',
  'barbecue butcher paper unwrap tailgate rig',
  'smoked brisket smoke ring reveal',
  'barbecue bbq sauce glaze steel prep counter',
  'barbecue rendered fat cap butcher shop case',
  'whole packer brisket picnic table spread',
  'beef ribs butcher shop case',
  'smoked chuck roast offset smoker firebox',
  'whole packer brisket sliced tailgate rig backlit smoke',
  'baby back ribs pit room embers',
  'pork belly burnt ends chimney smoke plume',
  'smoked brisket sliced pitmaster cutting board backlit smoke',
  'whole packer brisket pit room embers',
  'brisket bark slices chimney smoke plume',
  'barbecue pit room embers smokehouse dusk',
  'barbecue chimney smoke plume low and slow smokeout',
  'brisket bark slices pitmaster cutting board',
  'brisket bark slices bbq sauce glaze',
  'barbecue smoke ring reveal low and slow smokeout',
  'pulled pork shoulder pitmaster cutting board',
  'smoked sausage links smokehouse dusk',
  'smoked sausage links sliced smokehouse dusk backlit smoke',
  'barbecue slice board resting juices tailgate rig',
  'smoked chuck roast sliced tailgate rig backlit smoke',
  'whole packer brisket post-oak log pile',
  'barbecue butcher paper unwrap pitmaster cutting board',
  'smoked sausage links steel prep counter',
  'burnt ends pitmaster cutting board',
  'beef ribs sliced pitmaster cutting board amber hour',
  'burnt ends pit room embers',
  'burnt ends tailgate rig',
  'whole packer brisket sliced tailgate rig ember glow',
  'beef ribs sliced smokehouse dusk ember glow',
  'barbecue chimney smoke plume picnic table spread',
  'barbecue pit room embers pitmaster cutting board',
  'beef ribs tailgate rig',
  'burnt ends butcher shop case',
  'barbecue offset smoker firebox butcher shop case',
],
// Omakase & sushi
[
  'omakase sushi plating minimal',
  'omakase squid silk cut minimal plating',
  'ikura salmon roe ceramic slate plate',
  'sushi minimal negative space minimal',
  'sushi cedar box serve minimal',
  'omakase ikura salmon roe minimal plating',
  'wagyu sear nigiri chef plating tweezers',
  'uni gunkan hinoki counter',
  'sushi chef plating tweezers minimal',
  'hamachi yellowtail wasabi grater beside',
  'otoro nigiri matte ceramic mood',
  'sushi lacquer serving board minimal',
  'omakase hamachi yellowtail minimal plating',
  'otoro nigiri wasabi grater beside',
  'sushi hinoki counter minimal',
  'salmon roe gunkan lacquer serving board',
  'uni gunkan soft window light',
  'sushi wasabi grater beside minimal',
  'ikura salmon roe hinoki counter',
  'seared scallop nigiri bamboo leaf garnish',
  'uni gunkan counter spot light',
  'tamago slice bamboo leaf garnish',
  'squid silk cut hinoki counter',
  'omakase salmon roe gunkan minimal plating',
  'negitoro handroll bamboo leaf garnish',
  'omakase otoro nigiri minimal plating',
  'omakase tamago slice minimal plating',
  'sushi stone dishware minimal',
  'omakase seared scallop nigiri minimal plating',
  'uni gunkan matte ceramic mood',
  'wagyu sear nigiri counter spot light',
  'anago eel fillet counter spot light',
  'otoro nigiri cedar box serve',
  'tiger prawn nigiri soft window light',
  'tiger prawn nigiri counter spot light',
  'sushi bamboo leaf garnish minimal',
  'omakase anago eel fillet minimal plating',
  'omakase wagyu sear nigiri minimal plating',
  'omakase negitoro handroll minimal plating',
  'squid silk cut lacquer serving board',
  'tiger prawn nigiri stone dishware',
  'sushi ceramic slate plate minimal',
  'cured saba mackerel chef plating tweezers',
  'nigiri selection chef plating tweezers',
  'omakase hoe sashimi platter minimal plating',
  'cured saba mackerel soft window light',
  'omakase nigiri selection minimal plating',
  'omakase cured saba mackerel minimal plating',
  'negitoro handroll cedar box serve',
  'hamachi yellowtail counter spot light',
  'uni gunkan lacquer serving board',
  'omakase tiger prawn nigiri minimal plating',
  'nigiri selection counter spot light',
  'hoe sashimi platter lacquer serving board',
  'ikura salmon roe minimal negative space',
  'tamago slice counter spot light',
  'tiger prawn nigiri lacquer serving board',
  'tiger prawn nigiri matte ceramic mood',
  'hoe sashimi platter matte ceramic mood',
  'sushi tokonoma alcove backdrop minimal',
  'squid silk cut matte ceramic mood',
  'tiger prawn nigiri minimal negative space',
  'hamachi yellowtail matte ceramic mood',
  'ikura salmon roe soft window light',
  'nigiri selection soft window light',
  'salmon roe gunkan chef plating tweezers',
  'omakase uni gunkan minimal plating',
  'salmon roe gunkan wasabi grater beside',
  'tamago slice matte ceramic mood',
  'salmon roe gunkan minimal negative space',
  'cured saba mackerel tokonoma alcove backdrop',
  'seared scallop nigiri counter spot light',
  'wagyu sear nigiri soft window light',
  'salmon roe gunkan bamboo leaf garnish',
  'wagyu sear nigiri cedar box serve',
  'hoe sashimi platter bamboo leaf garnish',
  'anago eel fillet cedar box serve',
  'squid silk cut stone dishware',
  'seared scallop nigiri hinoki counter',
  'negitoro handroll soft window light',
  'negitoro handroll matte ceramic mood',
  'nigiri selection tokonoma alcove backdrop',
  'tamago slice soft window light',
  'uni gunkan ceramic slate plate',
  'tiger prawn nigiri ceramic slate plate',
  'negitoro handroll ceramic slate plate',
  'seared scallop nigiri tokonoma alcove backdrop',
  'otoro nigiri lacquer serving board',
  'otoro nigiri ceramic slate plate',
  'tiger prawn nigiri cedar box serve',
  'salmon roe gunkan soft window light',
  'hoe sashimi platter minimal negative space',
  'hoe sashimi platter soft window light',
  'nigiri selection cedar box serve',
  'wagyu sear nigiri lacquer serving board',
  'tamago slice wasabi grater beside',
  'tamago slice stone dishware',
  'seared scallop nigiri soft window light',
  'anago eel fillet soft window light',
  'anago eel fillet hinoki counter',
  'tamago slice minimal negative space',
  'hamachi yellowtail soft window light',
  'otoro nigiri counter spot light',
  'uni gunkan tokonoma alcove backdrop',
  'squid silk cut chef plating tweezers',
  'hoe sashimi platter chef plating tweezers',
  'squid silk cut counter spot light',
  'seared scallop nigiri chef plating tweezers',
  'seared scallop nigiri minimal negative space',
  'uni gunkan bamboo leaf garnish',
  'ikura salmon roe bamboo leaf garnish',
  'otoro nigiri bamboo leaf garnish',
  'wagyu sear nigiri wasabi grater beside',
  'ikura salmon roe lacquer serving board',
  'negitoro handroll stone dishware',
  'wagyu sear nigiri matte ceramic mood',
  'otoro nigiri soft window light',
  'ikura salmon roe counter spot light',
  'cured saba mackerel counter spot light',
  'hamachi yellowtail lacquer serving board',
  'uni gunkan stone dishware',
  'cured saba mackerel minimal negative space',
  'hamachi yellowtail hinoki counter',
  'cured saba mackerel matte ceramic mood',
  'negitoro handroll counter spot light',
  'hamachi yellowtail bamboo leaf garnish',
  'anago eel fillet ceramic slate plate',
  'tamago slice cedar box serve',
  'hamachi yellowtail ceramic slate plate',
  'otoro nigiri chef plating tweezers',
  'nigiri selection matte ceramic mood',
  'uni gunkan cedar box serve',
  'hoe sashimi platter counter spot light',
  'anago eel fillet matte ceramic mood',
  'salmon roe gunkan tokonoma alcove backdrop',
  'squid silk cut soft window light',
  'hoe sashimi platter cedar box serve',
  'tamago slice ceramic slate plate',
  'wagyu sear nigiri stone dishware',
  'tiger prawn nigiri wasabi grater beside',
],
// Picnics & outdoor spreads
[
  'summer picnic spread orchard blanket',
  'watermelon wedges orchard blanket',
  'gingham blanket layout summer afternoon light',
  'hilltop vista cloth sun-dappled shade',
  'orchard blanket string light dusk',
  'riverbank shade sun-dappled shade',
  'cider bottles blue sky picnic brightness',
  'apple grove hammock nearby sun-dappled shade',
  'cherry punnet spill hilltop vista cloth',
  'grape and cheese board blue sky picnic brightness',
  'jam jars and spoons riverbank shade',
  'cider bottles meadow afternoon',
  'lemonade pitcher string light dusk',
  'watermelon wedges warm backlight through grass',
  'grape and cheese board hilltop vista cloth',
  'lemonade pitcher warm backlight through grass',
  'summer picnic cider bottles summer afternoon light',
  'gingham blanket layout blue sky picnic brightness',
  'lavender field margin warm backlight through grass',
  'lavender field margin sun-dappled shade',
  'meadow afternoon summer afternoon light',
  'wildflower posy string light dusk',
  'wildflower posy blue sky picnic brightness',
  'wildflower posy summer afternoon light',
  'sandwich stack wrap sun-dappled shade',
  'straw hat detail summer afternoon light',
  'lemonade pitcher summer afternoon light',
  'meadow afternoon string light dusk',
  'cider bottles summer afternoon light',
  'lemonade pitcher blue sky picnic brightness',
  'wildflower posy lavender field margin',
  'lemonade pitcher birch grove clearing',
  'wildflower posy meadow afternoon',
  'cherry punnet spill string light dusk',
  'thermos and enamel cups birch grove clearing',
  'riverbank shade string light dusk',
  'lavender field margin summer afternoon light',
  'summer picnic cherry punnet spill summer afternoon light',
  'birch grove clearing warm backlight through grass',
  'summer picnic straw hat detail sun-dappled shade',
  'thermos and enamel cups blue sky picnic brightness',
  'sandwich stack wrap birch grove clearing',
  'meadow afternoon sun-dappled shade',
  'strawberry tartlets sun-dappled shade',
  'baguette and brie hilltop vista cloth',
  'cherry punnet spill warm backlight through grass',
  'summer picnic wildflower posy warm backlight through grass',
  'hilltop vista cloth warm backlight through grass',
  'gingham blanket layout warm backlight through grass',
  'orchard blanket warm backlight through grass',
  'cherry punnet spill blue sky picnic brightness',
  'summer picnic cider bottles blue sky picnic brightness',
  'lattice pie blue sky picnic brightness',
  'birch grove clearing string light dusk',
  'cherry punnet spill birch grove clearing',
  'grape and cheese board meadow afternoon',
  'straw hat detail hilltop vista cloth',
  'riverbank shade summer afternoon light',
  'grape and cheese board riverbank shade',
  'vineyard edge string light dusk',
  'sandwich stack wrap riverbank shade',
  'gingham blanket layout lavender field margin',
  'summer picnic sandwich stack wrap summer afternoon light',
  'summer picnic wildflower posy summer afternoon light',
  'summer picnic grape and cheese board sun-dappled shade',
  'birch grove clearing sun-dappled shade',
  'straw hat detail sun-dappled shade',
  'lemonade pitcher meadow afternoon',
  'meadow afternoon blue sky picnic brightness',
  'birch grove clearing summer afternoon light',
  'cider bottles sun-dappled shade',
  'lattice pie string light dusk',
  'vineyard edge sun-dappled shade',
  'apple grove hammock nearby warm backlight through grass',
  'grape and cheese board birch grove clearing',
  'summer picnic wicker basket spread sun-dappled shade',
  'cherry punnet spill vineyard edge',
  'cider bottles string light dusk',
  'summer picnic straw hat detail string light dusk',
  'straw hat detail birch grove clearing',
  'sandwich stack wrap meadow afternoon',
  'gingham blanket layout vineyard edge',
  'summer picnic watermelon wedges blue sky picnic brightness',
  'thermos and enamel cups riverbank shade',
  'summer picnic cider bottles warm backlight through grass',
  'lemonade pitcher lavender field margin',
  'summer picnic lemonade pitcher summer afternoon light',
  'summer picnic gingham blanket layout summer afternoon light',
  'summer picnic jam jars and spoons sun-dappled shade',
  'apple grove hammock nearby summer afternoon light',
  'watermelon wedges summer afternoon light',
  'summer picnic gingham blanket layout string light dusk',
  'summer picnic strawberry tartlets blue sky picnic brightness',
  'hilltop vista cloth blue sky picnic brightness',
  'thermos and enamel cups summer afternoon light',
  'straw hat detail warm backlight through grass',
  'jam jars and spoons warm backlight through grass',
  'strawberry tartlets orchard blanket',
  'summer picnic watermelon wedges summer afternoon light',
  'lemonade pitcher orchard blanket',
  'summer picnic sandwich stack wrap string light dusk',
  'summer picnic sandwich stack wrap sun-dappled shade',
  'baguette and brie meadow afternoon',
  'gingham blanket layout apple grove hammock nearby',
  'apple grove hammock nearby blue sky picnic brightness',
  'watermelon wedges sun-dappled shade',
  'sandwich stack wrap warm backlight through grass',
  'grape and cheese board warm backlight through grass',
  'wildflower posy warm backlight through grass',
  'wildflower posy hilltop vista cloth',
  'cider bottles apple grove hammock nearby',
  'thermos and enamel cups vineyard edge',
  'baguette and brie vineyard edge',
  'lemonade pitcher apple grove hammock nearby',
  'jam jars and spoons lavender field margin',
  'summer picnic strawberry tartlets warm backlight through grass',
  'lavender field margin blue sky picnic brightness',
  'straw hat detail riverbank shade',
  'thermos and enamel cups string light dusk',
  'gingham blanket layout sun-dappled shade',
  'vineyard edge summer afternoon light',
  'strawberry tartlets warm backlight through grass',
  'thermos and enamel cups apple grove hammock nearby',
  'summer picnic lattice pie blue sky picnic brightness',
  'lattice pie sun-dappled shade',
  'summer picnic watermelon wedges sun-dappled shade',
  'summer picnic wildflower posy sun-dappled shade',
  'summer picnic wicker basket spread string light dusk',
  'cherry punnet spill summer afternoon light',
  'thermos and enamel cups hilltop vista cloth',
  'straw hat detail lavender field margin',
  'straw hat detail string light dusk',
  'gingham blanket layout orchard blanket',
  'summer picnic lemonade pitcher string light dusk',
  'summer picnic thermos and enamel cups sun-dappled shade',
  'thermos and enamel cups sun-dappled shade',
  'wicker basket spread summer afternoon light',
  'vineyard edge warm backlight through grass',
  'summer picnic watermelon wedges warm backlight through grass',
  'summer picnic baguette and brie sun-dappled shade',
],
// Chocolate & dessert
[
  'melted chocolate pouring swirl',
  'praline cut rows swirl',
  'tempered marble sheen swirl',
  'ganache ribbon drip dark moody light',
  'melted chocolate pouring warm studio glow',
  'chocolate pouring macro detail',
  'chocolate swirl gloss highlight',
  'chocolate drip gloss highlight',
  'chocolate swirl fold specular gloss light',
  'brownie fudge squares on copper saucepan',
  'tempered marble sheen on matte black bowl',
  'chocolate pouring gloss highlight',
  'melted chocolate pouring on parchment lined tray',
  'cocoa dusted truffles swirl',
  'chocolate drip slow motion feel',
  'fondue slow dip on gold flake finish',
  'ganache ribbon drip swirl',
  'tempered marble sheen warm studio glow',
  'ganache ribbon drip on matte black bowl',
  'chocolate bark shards swirl',
  'fondue slow dip warm studio glow',
  'molten lava center warm studio glow',
  'chocolate curl shavings specular gloss light',
  'chocolate swirl macro detail',
  'chocolate swirl slow motion feel',
  'chocolate curl shavings swirl',
  'cocoa dusted truffles on matte black bowl',
  'molten lava center dark moody light',
  'chocolate swirl fold on matte black bowl',
  'chocolate pouring slow motion feel',
  'cacao nib scatter on dark slate backdrop',
  'cocoa dusted truffles specular gloss light',
  'praline cut rows on deep burgundy velvet',
  'tempered marble sheen on deep burgundy velvet',
  'chocolate curl shavings on marble slab',
  'ganache ribbon drip warm studio glow',
  'drizzled whisk lift warm studio glow',
  'fondue slow dip swirl',
  'ganache ribbon drip specular gloss light',
  'melted chocolate pouring dark moody light',
  'drizzled whisk lift on deep burgundy velvet',
  'chocolate swirl fold swirl',
  'tempered marble sheen on dark slate backdrop',
  'cacao nib scatter swirl',
  'cacao nib scatter on gold flake finish',
  'chocolate curl shavings on dark slate backdrop',
  'chocolate bark shards specular gloss light',
  'cocoa dusted truffles on dark slate backdrop',
  'cacao nib scatter warm studio glow',
  'molten lava center on parchment lined tray',
  'melted chocolate pouring specular gloss light',
  'cacao nib scatter on deep burgundy velvet',
  'chocolate bark shards warm studio glow',
  'whipped chocolate mousse peak specular gloss light',
  'molten lava center specular gloss light',
  'whipped chocolate mousse peak dark moody light',
  'fondue slow dip on dark slate backdrop',
  'chocolate curl shavings on parchment lined tray',
  'melted chocolate pouring on copper saucepan',
  'drizzled whisk lift specular gloss light',
  'molten lava center on deep burgundy velvet',
  'molten lava center swirl',
  'melted chocolate pouring on gold flake finish',
  'whipped chocolate mousse peak swirl',
  'molten lava center on confectionery cooling rack',
  'chocolate curl shavings on deep burgundy velvet',
  'chocolate swirl fold on copper saucepan',
  'whipped chocolate mousse peak on copper saucepan',
  'drizzled whisk lift swirl',
  'cacao nib scatter dark moody light',
  'fondue slow dip on copper saucepan',
  'praline cut rows dark moody light',
  'chocolate drip macro detail',
  'praline cut rows warm studio glow',
  'tempered marble sheen on copper saucepan',
  'chocolate swirl fold on dark slate backdrop',
  'chocolate swirl fold dark moody light',
  'brownie fudge squares swirl',
  'brownie fudge squares on matte black bowl',
  'tempered marble sheen specular gloss light',
  'chocolate curl shavings warm studio glow',
  'cocoa dusted truffles dark moody light',
  'cocoa dusted truffles on deep burgundy velvet',
  'ganache ribbon drip on deep burgundy velvet',
  'fondue slow dip dark moody light',
  'chocolate swirl fold on confectionery cooling rack',
  'drizzled whisk lift on marble slab',
  'fondue slow dip specular gloss light',
  'fondue slow dip on confectionery cooling rack',
  'chocolate swirl fold warm studio glow',
  'brownie fudge squares warm studio glow',
  'cacao nib scatter specular gloss light',
  'chocolate bark shards on parchment lined tray',
  'brownie fudge squares specular gloss light',
  'molten lava center on copper saucepan',
  'fondue slow dip on matte black bowl',
  'cacao nib scatter on confectionery cooling rack',
  'drizzled whisk lift on matte black bowl',
  'tempered marble sheen dark moody light',
  'cacao nib scatter on marble slab',
  'cocoa dusted truffles on parchment lined tray',
  'chocolate bark shards on deep burgundy velvet',
  'cocoa dusted truffles on copper saucepan',
  'drizzled whisk lift on copper saucepan',
  'whipped chocolate mousse peak on confectionery cooling rack',
  'ganache ribbon drip on copper saucepan',
  'ganache ribbon drip on marble slab',
  'chocolate swirl fold on parchment lined tray',
  'melted chocolate pouring on confectionery cooling rack',
  'fondue slow dip on parchment lined tray',
  'melted chocolate pouring on marble slab',
  'chocolate bark shards on matte black bowl',
  'chocolate bark shards on confectionery cooling rack',
  'chocolate curl shavings on matte black bowl',
  'chocolate bark shards dark moody light',
  'whipped chocolate mousse peak on parchment lined tray',
  'praline cut rows on confectionery cooling rack',
  'whipped chocolate mousse peak on marble slab',
  'brownie fudge squares on deep burgundy velvet',
  'chocolate bark shards on marble slab',
  'whipped chocolate mousse peak warm studio glow',
  'brownie fudge squares dark moody light',
  'tempered marble sheen on confectionery cooling rack',
  'ganache ribbon drip on parchment lined tray',
  'fondue slow dip on marble slab',
  'cocoa dusted truffles warm studio glow',
  'tempered marble sheen on marble slab',
  'drizzled whisk lift on parchment lined tray',
  'praline cut rows on copper saucepan',
  'drizzled whisk lift on gold flake finish',
  'chocolate swirl fold on marble slab',
  'cocoa dusted truffles on confectionery cooling rack',
  'brownie fudge squares on parchment lined tray',
  'praline cut rows on parchment lined tray',
  'drizzled whisk lift dark moody light',
  'chocolate curl shavings on confectionery cooling rack',
  'molten lava center on gold flake finish',
  'chocolate bark shards on dark slate backdrop',
  'cocoa dusted truffles on marble slab',
  'molten lava center on marble slab',
]
];

const QUERY_GROUPS: readonly (readonly string[])[] = [LEGACY_SEARCH_QUERIES, ...FOOD_SEARCH_QUERY_GROUPS];
const QUERIES: readonly string[] = QUERY_GROUPS.flat();
const FAMILY_INDEX_BY_QUERY = new Map<string, number>();
QUERY_GROUPS.forEach((group, familyIndex) => {
  for (const query of group) FAMILY_INDEX_BY_QUERY.set(query, familyIndex);
});

/** Up to eight sibling pages from the same topical family, cycling within it. */
export function relatedSearchPages(entry: CuratedSearchPage): CuratedSearchPage[] {
  const siblings = CURATED_SEARCH_PAGES.filter((page) => page.familyIndex === entry.familyIndex && page.slug !== entry.slug);
  if (siblings.length === 0) return [];
  const start = CURATED_SEARCH_PAGES.indexOf(entry);
  const first = siblings.findIndex((page) => CURATED_SEARCH_PAGES.indexOf(page) > start);
  const offset = first === -1 ? 0 : first;
  return Array.from({ length: Math.min(8, siblings.length) }, (_, i) => siblings[(offset + i) % siblings.length]);
}

function slugify(query: string): string {
  return query
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const SMALL_WORDS = new Set(['and', 'of', 'the', 'with', 'for', 'in', 'on', 'at', 'from']);

function titleize(query: string): string {
  const words = query.split(' ');
  return words
    .map((word, index) => {
      if (index > 0 && SMALL_WORDS.has(word)) return word;
      return word
        .split('-')
        .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part))
        .join('-');
    })
    .join(' ');
}

const BLURB_TEMPLATES: readonly ((title: string, lower: string) => string)[] = [
  (title, lower) => `Browse a curated set of ${lower} images generated with ManifoldGen. Open any result in Studio to remix the prompt into your own image or video.`,
  (title, lower) => `${title}, rendered by ManifoldGen: a hand-picked gallery of AI-generated frames with full prompts you can copy, restyle, and animate.`,
  (_title, lower) => `Explore ${lower} through AI image generation. Every thumbnail links back to its prompt so you can recreate the look in ManifoldGen Studio.`,
  (_title, lower) => `An AI-generated ${lower} gallery curated from the public ManifoldGen explore feed. Click any frame to open the original prompt.`,
  (_title, lower) => `See how ManifoldGen interprets ${lower}. Each result keeps its prompt attached so you can iterate on lighting, mood, and composition.`,
  (_title, lower) => `AI-generated ${lower}, curated by the ManifoldGen team for prompt inspiration. Remix any frame into video or a fresh still inside Studio.`,
];

export const CURATED_SEARCH_PAGES: CuratedSearchPage[] = QUERIES.map((query, index) => {
  const title = titleize(query);
  return {
    slug: slugify(query),
    query,
    title,
    blurb: BLURB_TEMPLATES[index % BLURB_TEMPLATES.length](title, query.toLowerCase()),
    familyIndex: FAMILY_INDEX_BY_QUERY.get(query) ?? 0,
  };
});
