export type ToolCard = {
  href: string;
  name: string;
  label: string;
  copy: string;
  kind: 'image' | 'video' | 'audio';
  src: string;
  meta: string;
  layout?: 'hero' | 'wide' | 'tall';
};

export const TOOL_CDN = 'https://manifoldgenstatic.manifoldgen.com/gallery';

export const tools: readonly ToolCard[] = [
  { href: '/tools/character-swap', name: 'Character Swap Music Video', label: 'PERFORMER SWAP', copy: 'Redraw the first frame with new characters, then H3 re-performs every shot with the same moves on the original soundtrack.', kind: 'video', src: 'https://manifoldgenstatic.manifoldgen.com/static/tools/character-swap/rapvid-elon-optimus.mp4', meta: 'GPT Image 2 frame · MiniMax H3 reference-to-video · original audio', layout: 'hero' },
  { href: '/tools/character-swap-exact', name: 'Exact Motion Character Swap', label: 'FRAME-EXACT SWAP', copy: 'Replace each performer inside the original footage with pose-exact motion transfer; cuts, camera and soundtrack untouched.', kind: 'video', src: 'https://manifoldgenstatic.manifoldgen.com/static/tools/character-swap/rapvid-elon-optimus-exact.mp4', meta: 'GPT Image 2 frame · Wan 2.2 Animate per performer · YOLO pose composite' },
  { href: '/tool/anima', name: 'Anima Art Studio', label: 'CHARACTER ART', copy: 'Anime-native character design and polished illustration.', kind: 'image', src: '/examples/anima/celestial-cartographer.png', meta: 'Anima-2.9B · seed 18467291', layout: 'tall' },
  { href: '/tools/make-image', name: 'Make Image', label: 'BULK TEXT TO IMAGE', copy: 'Generate many variants at once with RA2, one prompt per line.', kind: 'image', src: `${TOOL_CDN}/originals/f494f664998c53f0_10658d95.webp`, meta: 'RA2 · multi-variant · $0.04 per image', layout: 'tall' },
  { href: '/tools/cinematic-cameras', name: 'Cinematic Cameras', label: 'CAMERA CONTROL', copy: 'Image generation steered by dolly, crane, macro, and lens-direction presets.', kind: 'image', src: `${TOOL_CDN}/originals/d9e1b11a3ec6e66f_22e5d455.webp`, meta: 'RA2 · GPT Image 2 · camera presets' },
  { href: '/tools/relight', name: 'Relight', label: 'LIGHTING CONTROL', copy: 'Move the key light. Adjust direction and mood of any photo with IC-Light v2.', kind: 'image', src: `${TOOL_CDN}/originals/h3_dev_glass_hummingbird_greenhouse_20260816.png`, meta: 'fal IC-Light v2 · directional relighting' },
  { href: '/tools/inpaint', name: 'Inpaint', label: 'MASKED EDITING', copy: 'Brush an area, describe the change—everything outside your mask stays pixel-identical.', kind: 'image', src: `${TOOL_CDN}/originals/15bda460daa1596f_6e5ce65c.webp`, meta: 'GPT Image 2 edit · feathered mask composite' },
  { href: '/tools/image-upscale', name: 'Image Upscale', label: 'ENHANCE', copy: '2x creative upscaling that recovers texture and detail without plastic artifacts.', kind: 'image', src: `${TOOL_CDN}/originals/ea0d66c5b19b8439_64411e9f.webp`, meta: 'fal creative-upscaler · 2x' },
  { href: '/tools/outpaint', name: 'Extend Image', label: 'OUTPAINTING', copy: 'Grow the canvas in any direction or zoom out while the scene keeps extending.', kind: 'image', src: `${TOOL_CDN}/originals/64171ef03cb954ad_378dad88.webp`, meta: 'extend-image · expand or zoom out' },
  { href: '/tools/moodboard', name: 'Soul Moodboard', label: 'REFERENCES', copy: 'Drop 2–6 references and fuse them into one focused visual direction.', kind: 'image', src: `${TOOL_CDN}/originals/e681e42f9ad635c1_45a810ec.webp`, meta: 'Nano Banana 2 · GPT Image 2 · multi-reference' },
  { href: '/tools/nano-banana', name: 'Nano Banana 2', label: 'IMAGE MODEL', copy: 'Google Gemini-flash image generation and reference editing at speed.', kind: 'image', src: `${TOOL_CDN}/originals/2cd11733526df0ed_6e875ea4.webp`, meta: 'or/gemini-3.1-flash-image via OpenPaths' },
  { href: '/tools/grok-imagine', name: 'Grok Imagine 2.0', label: 'IMAGE MODEL', copy: 'High-resolution image generation by xAI with 2K quality tier.', kind: 'image', src: `${TOOL_CDN}/originals/8393bf4dfc931639_c83b5040.webp`, meta: 'grok-imagine-image · 1K/2K' },
  { href: '/tools/flux-2', name: 'FLUX.2', label: 'IMAGE MODEL', copy: 'Speed-optimized detail from Klein, Dev, and Pro lanes.', kind: 'image', src: `${TOOL_CDN}/originals/ea0d66c5b19b8439_64411e9f.webp`, meta: 'FLUX.2 Klein · Dev · Pro' },
  { href: '/tools/gpt-image', name: 'GPT Image 2', label: 'IMAGE MODEL', copy: '4K-capable images with near-perfect text rendering.', kind: 'image', src: `${TOOL_CDN}/originals/d9e1b11a3ec6e66f_22e5d455.webp`, meta: 'gpt-image-2 · always metered' },
  { href: '/tools/style-transfer', name: 'Style Transfer', label: 'IMAGE EDITING', copy: 'Upload a source image, describe a new visual world, and keep the composition while the edit runs.', kind: 'image', src: `${TOOL_CDN}/originals/40dd7bf2dc3aa527_8289a523.webp`, meta: 'OpenPaths image-edit · GPT Image 2 route', layout: 'tall' },
  { href: '/tools/h3-image', name: 'H3 Image', label: 'TEXT TO IMAGE', copy: 'High-detail finished frames from the H3 visual world model.', kind: 'image', src: `${TOOL_CDN}/originals/h3_dev_glass_hummingbird_20260816.png`, meta: 'MiniMax H3 · real generation' },
  { href: '/tools/h3-image-editor', name: 'H3 Image Editor', label: 'REFERENCE EDIT', copy: 'Regenerate a source while preserving identity and geometry.', kind: 'image', src: `${TOOL_CDN}/originals/h3_dev_glass_hummingbird_greenhouse_20260816.png`, meta: 'H3 REF2VA · real edit' },
  { href: '/tools/character-animator', name: 'Character Animator', label: 'IMAGE + MOTION', copy: 'Transfer body movement, expression, and timing from a driving clip.', kind: 'video', src: `${TOOL_CDN}/videos/wan_animate_cartographer_standard_5s_20260816.mp4`, meta: 'Wan Animate 2 · real 5s Standard output', layout: 'wide' },
  { href: '/tool/animate-video?mode=move', name: 'Wan Animate Move', label: 'MOVE IMAGE', copy: 'Make a complete reference image follow a driving performance.', kind: 'video', src: `${TOOL_CDN}/originals/cde50c0ae9ea7c5e_038928f6.webp`, meta: 'Wan 2.2 Animate · Move · 480p–720p', layout: 'tall' },
  { href: '/tool/animate-video?mode=replace', name: 'Wan Animate Replace', label: 'REPLACE CHARACTER', copy: 'Swap the performer while keeping the source video scene and lighting.', kind: 'video', src: `${TOOL_CDN}/originals/5e8e6b5cf80f67d5_6e242271.webp`, meta: 'Wan 2.2 Animate · Replace · 480p–720p', layout: 'tall' },
  { href: '/tools/pose-video', name: 'Pose Video Transfer', label: 'CONTROL VIDEO', copy: 'Turn a driving performance into a witch, mage, creature, or completely new character.', kind: 'video', src: 'https://huggingface.co/alibaba-pai/MiniMax-H3-Fun-Controlnet-Union/resolve/main/asset/pose_dance.mp4', meta: 'Pose motion control · ordinary video or prepared pass' },
  { href: '/tools/depth-video', name: 'Depth Video Control', label: 'VIDEO STYLE TRANSFER', copy: 'Rebuild a clip while preserving moving depth, camera path, and spatial volume.', kind: 'video', src: 'https://huggingface.co/alibaba-pai/MiniMax-H3-Fun-Controlnet-Union/resolve/main/asset/depth_astronaut.mp4', meta: 'Depth control · ordinary video or prepared pass' },
  { href: '/tools/canny-video', name: 'Canny Video Control', label: 'VIDEO STYLE TRANSFER', copy: 'Keep silhouettes and motion locked while redrawing every frame in a new world.', kind: 'video', src: 'https://huggingface.co/alibaba-pai/MiniMax-H3-Fun-Controlnet-Union/resolve/main/asset/canny_tokyo_street.mp4', meta: 'Canny edge control · ordinary video or prepared pass' },
  { href: '/tools/hed-video', name: 'HED Video Control', label: 'VIDEO STYLE TRANSFER', copy: 'Preserve soft organic contours for expressive creature, face, and illustration transfer.', kind: 'video', src: 'https://huggingface.co/alibaba-pai/MiniMax-H3-Fun-Controlnet-Union/resolve/main/asset/hed_trex_bmx.mp4', meta: 'HED contour control · ordinary video or prepared pass' },
  { href: '/tools/mlsd-video', name: 'MLSD Video Control', label: 'ARCHITECTURE CONTROL', copy: 'Hold straight lines and perspective stable while transforming designed spaces.', kind: 'video', src: 'https://huggingface.co/alibaba-pai/MiniMax-H3-Fun-Controlnet-Union/resolve/main/asset/mlsd_village.mp4', meta: 'MLSD line control · ordinary video or prepared pass' },
  { href: '/tools/video-background-remover', name: 'Video Background Remover', label: 'VIDEO UTILITY', copy: 'Create a transparent foreground while retaining original pixels.', kind: 'video', src: `${TOOL_CDN}/service_netw/video-background/6f378c9b-1c0d-4aad-9f1a-e41f9436fca5.webm`, meta: 'RVM · real transparent output' },
  { href: '/tools/video-remake', name: 'Video Remake Agent', label: 'FULL-LENGTH RESTYLE', copy: 'Detect every shot, guide a coherent restyle, and preserve the exact timeline and soundtrack.', kind: 'video', src: `${TOOL_CDN}/videos/wan_animate_cartographer_standard_5s_20260816.mp4`, meta: 'DeepSeek vision · GPT Image / Nano Banana · H3 Max motion', layout: 'wide' },
  { href: '/tools/trailer-agent', name: 'Cinematic Trailer Agent', label: 'BRIEF TO TRAILER', copy: 'Sketch characters, lock identity sheets, repair drift, then animate accepted start frames with Gemini speech, a score, and H3.', kind: 'video', src: `${TOOL_CDN}/originals/a22d4658c1218324_1c0bd993.webp`, meta: 'RA2 sketch · GPT Image 2 · Gemini TTS · H3 · Manifold music', layout: 'wide' },
  { href: '/tools/music-generator', name: 'Manifold Music Generator', label: 'MUSIC', copy: 'Describe a song; an LLM writes the arrangement and lyrics, then the Manifold music model records a full 48 kHz stereo track.', kind: 'audio', src: `${TOOL_CDN}/originals/937db95cc67cd643_4979a0d3.webp`, meta: 'LLM composer · Manifold music model · 48 kHz stereo', layout: 'wide' },
  { href: '/tools/lofi-loop', name: 'Lofi Loop Studio', label: 'LOOPING VIDEO', copy: 'Turn any track into a seamless looping lofi video with generated cover art and an audio visualizer.', kind: 'video', src: `${TOOL_CDN}/originals/cae9cf39d759fd21_6571311b.webp`, meta: 'RA2 cover · parallax loop · 6 visualizers', layout: 'wide' },
  { href: '/tools/lyria', name: 'Lyria 3 Music Studio', label: 'GOOGLE MUSIC', copy: 'Direct full songs, scores, vocal hooks, and loops with timed structure and compact Opus output.', kind: 'audio', src: `${TOOL_CDN}/originals/cc71ca9bddd14b21_1d2c6cb3.webp`, meta: 'Lyria 3 Pro · Clip · OpenPaths · 44.1 kHz stereo' },
  { href: '/tools/gemini-tts', name: 'Gemini Voice Director', label: 'MULTI-SPEAKER TTS', copy: 'Stage expressive narration and two-person scenes with 30 voices, accents, pace, and emotion cues.', kind: 'audio', src: `${TOOL_CDN}/originals/9cb157dc2ac94ec0_647be069.webp`, meta: 'Gemini 3.1 Flash TTS · OpenPaths · 30 voices' },
  { href: '/voice', name: 'Voice Studio', label: 'TEXT TO SPEECH', copy: 'Expressive narration, dialogue, and audio scenes from a script across seven voice models.', kind: 'audio', src: `${TOOL_CDN}/originals/fc1889c2bf8c3f72_55fdc1c3.webp`, meta: 'Seed Audio · ElevenLabs v3 · Gemini Voice', layout: 'tall' },
];
